### ISSUE TITLE
EnderDragons

### ISSUE THREAD

**Issue by DrkMatr1984** [timbru31/SilkSpawners#10]
Hmm, I thought in the 1.7 version I could change the spawners to EnderDragons. Do you plan to reimplement this or is it off the shelf for good? It doesn't seem to work in 1.8.

**Comment by timbru31** [comment]
Are you able to set the type of the spawner and the mob is just not spawning?
Because I do not modify the spawning algorithm.

You could enable "spawnEggOverride" and then spawn the Enderdragon via an egg however.

**Comment by DrkMatr1984** [comment]
Hmmm, It seems no matter what I can't change the spawner-type to EnderDragon. If I use a spawn egg it says "Successfully Changed Spawner Type to RyeDragon" and normal /spawner EnderDragon or other aliases won't work either. Spawn Eggs do seem to work normally for EnderDragons. 
I hadn't seen anyone else report the issue so I thought I had better zip on over to you and let you know.  I just checked my config.yml and I do have spawnEggOverride enabled. Here's a copy of my config.yml for you to check out.
<addr>
# See documentation at http://dev.bukkit.org/bukkit-plugins/silkspawners/pages/configuration
 

# Should the plugin automatically update if an update is available?
autoUpdater: false
 

# Should permissions be used
usePermissions: true
 

# Should a permission be required when a spawner explodes by TNT to achieve a drop
permissionExplode: false
 

# Should be checked for WorldGuard build ability to change spawners
useWorldGuard: false
 

# Percentage of dropping a spawner block when TNT or creepers explode
explosionDropChance: 5
 

# Percentage of dropping a iron bars when a spawner is mined
destroyDropChance: 100
 

# Percentage of dropping an egg when a spawner is mined
eggDropChance: 100
 

# Percentage of dropping the spawner when mined
silkDropChance: 100
 

# When generic spawner items are placed, spawn this creature (e.g. from /give or other plugins)

# PIG (90) is Minecraft default (put NAMES or IDs here!)
defaultCreature: 90
 

# How far is the spawner reachable with your crosshair
spawnerCommandReachDistance: 6
 

# Minimum silk touch level [can be changed via other plugins to a higher value]

# Set it to 0 to mine it without silk touch
minSilkTouchLevel: 1
 

# If a player in creative destroys a spawner nothing is dropped
noDropsCreative: true
 

# If a spawner is destroyed, should the egg be dropped
destroyDropEgg: false
 

# If a spawner is destroyed, should XP be dropped
destroyDropXP: 0
 

# Flag a spawner as already mined to prevent XP duping
preventXPFarming: true
 

#Drops XP only when a spawner is destroyed and not mined via SilkTouch
dropXPOnlyOnDestroy: false
 

# If a spawner is destroyed, should iron bars be dropped
destroyDropBars: 0
 

# Should the player be able to craft spawners
craftableSpawners: false
 

# Leave a slot empty (null/air)? Just make a space then, example 'A A' -> middle is free

# X is always the egg
recipeTop: AAA
recipeMiddle: AXA
recipeBottom: AAA
recipeAmount: 1
 

# Custom example:

#recipeTop: 'A A'

#recipeMiddle: 'BXA'

#recipeBottom: 'C D'

#ingredients:

#  - 'A,IRON_FENCE'

#  - 'B,DIRT'

#  - 'C,2'

#  - 'D,5'

 

# You can put IDs or the NAME here (please uppercase)

# Add it for each custom ingredient you add, too!
ingredients:
- A,IRON_FENCE
 

# Should spawners be stackable
spawnersUnstackable: true
 

# Should the egg be consumed when the spawner is changed with it
consumeEgg: true
 

# Fallback if the creature should be enabled, if not specified for the entity
enableCreatureDefault: true
 

# Should numbers be ignored (on eggs) and allow every number value?
ignoreCheckNumbers: false
 

# Should instead of spawning a mob a MonsterSpawner be placed? (Uses consumeEgg value, too)
spawnEggToSpawner: false
 

# Should the spawn algorithm be overridden? Allows spawning of non-standard entities
spawnEggOverride: true
 

# Fallback if the creature should be spawned, if not specified for the entity
spawnEggOverrideSpawnDefault: true
 

# Notify the player about the spawner when he clicks it in the inventory
notifyOnClick: true
 

# Notify the player about the spawner when he holds the spawner in the hand
notifyOnHold: true
 

# Configure displaying with BarAPI, time is in seconds
barAPI:
  enable: true
  displayTime: 3
 

# Puts more information out on startup
verboseConfig: false
 

# Internal stuff, do NOT change unless advised - the plugin might break otherwise
useReflection: true
testMCVersion: true
useMetadata: true
useLegacyName: false

</addr>

**Comment by timbru31** [comment]
Sorry for my late response, I was busy the last weeks.
With spawnEggOverride: true I was able to spawn the enderdragon via an egg and the spawner changed to the EnderDragon, too. (however as expected no dragon spawned naturally)

**Comment by DrkMatr1984** [comment]
Oh ok, So you can change it to a EnderDragon but no EnderDragon Spawns... Is there a way to add code that detects what type of spawner it is and then spawn things on a runnable for a for loop that detects how many of those types of creatures are nearby? Perhaps I could code a small add-on for this like "Silk-Spawners EnderDragons" if you don't want to include the code. Then I can use your API to detect if it's a SIlkSpawner Spawner and what type it is.

**Comment by timbru31** [comment]
Technically this would be possible, the addon idea sounds IMO more suitable, however. (I always tried to exclude to modify the spawning algorithm of Minecraft)
Feel free to develop such an addon, if you need API addition/fixes/changes just open a new ticket :+1:

**Comment by DrkMatr1984** [comment]
One quick question. Are there any other entities that behave similar? If were to code an add-on, I might as well fill in the blanks where SilkSpawners leaves off and design this for the other missing spawns.
