### ISSUE TITLE
SlimeFun Integration

### ISSUE THREAD

**Issue by Faicu** [timbru31/SilkSpawners#100]
## What steps will reproduce the problem?
Using SlimeFun Spawners on a Server with SilkSpawners too

## Expected output
Spawners it's automatically changed to default spawner, Pig, due invalid data.

## What do you see instead?
Pig Spawner

## Log file of the issue/error
There is no error on Console etc.

## /version output?
git-Spigot-93e20b3-31d3159 (MC: 1.12.2)

## SilkSpawners version
SilkSpawners v5.0.1-SNAPSHOT-b448

## Please provide any additional information below.
So, after I make a Spawner with SlimeFun and I try to put it down, SilkSpawners it's interacting with this action and because SlimeFun it's storing the Spawner name in this lore, SilkSpawners it's considering it invalid because of this data and it's transforming it to default spawners, setup on config, pig.

## Checklist

- [X] I am aware that issues caused by /reload are ignored
- [X] If there is a (potential) plugin conflict, I've identified the conflicting plugin
- [X] I have added a valid /version output
- [X] I have added a valid SilkSpawners version
- [X] I have attached necessary information like a screenshot, my list of plugins, config or permissions file(s)

**Comment by timbru31** [comment]
Can you link the SlimeFun plugin, please? (if possible the GitHub repo)

**Comment by Faicu** [comment]
https://github.com/TheBusyBiscuit/Slimefun4
