### ISSUE TITLE
Monster Egg with ShopGUI+ and SilkSpawners

### ISSUE THREAD

**Issue by aurel85** [timbru31/SilkSpawners#101]
Hi,

In ShopGUI+ I sell mob eggs so that my players can change the spawners (I use SilkSpawners).
But as soon as I use an egg bought in the Admin Shop through ShopGUI + the spawner does not change and is completely broken as evidenced by the messages of SilkSpawners :

https://sandbox.fr/images/uploads/original/1511216319.png

And when I destroy it it disappears leaving this message.

https://sandbox.fr/images/uploads/original/1511216338.png

When I give myself eggs via the creative mode, there is no problem.

I use the last version of this plugin (5.0.0) and PaperSpigot 1.12.2.

**Comment by aurel85** [comment]
By removing SilkSpawners I no longer have this problem so the problem comes from SilkSpawners.
Thank you in advance for the debug.

**Comment by aurel85** [comment]
Hi,

Can I hope for a solution with the 1.13 ?

**Comment by timbru31** [comment]
Is this still an issue?

**Comment by aurel85** [comment]
Yes

**Comment by timbru31** [comment]
v6.0.1 has been released. If this issue persists, please create a new one. Thanks!
