### ISSUE TITLE
Error conflicting with another plugin

### ISSUE THREAD

**Issue by KillauraHacks** [timbru31/SilkSpawners#107]
## What steps will reproduce the problem?
Downloading SilkSpawners and Latest Version of ShopGUI+
## Expected output
No Errors
## What do you see instead?
Errors
## Log file of the issue/error
https://pastebin.com/0NQwusXv
## /version output?
SilkSpawners - 5.0.0 ShopGUI+ - 1.15.0

## SilkSpawners version
SilkSpawners - 5.0.0

## Checklist

- [x] I am aware that issues caused by /reload are ignored
- [x] If there is a (potential) plugin conflict, I've identified the conflicting plugin
- [ ] I have added a valid /version output
- [x] I have added a valid SilkSpawners version
- [x] I have attached necessary information like a screenshot, my list of plugins, config or permissions file(s)

**Comment by timbru31** [comment]
This seems related to using the API in a thread. Sadly ShopGUI+ is closed source, so I can't see the source code. I'll do some testing which involves using SilkSpawners in a debug plugin in order to see if I can reproduce the error.

**Comment by KillauraHacks** [comment]
Could it be that ShopGUIPlus is loading before SilkSpawners?

**Comment by KillauraHacks** [comment]
04.01 06:20:52 [Server] INFO at de.dustplanet.util.SilkUtil.getWorldGuard(SilkUtil.java:913) ~[?:?]
Could it be a problem with the worldguard support?

**Comment by timbru31** [comment]
Did it work for you before or are you setting up a new server?

**Comment by timbru31** [comment]
Can you give https://ci.dustplanet.de/job/SilkSpawners/452/ a try please?

**Comment by timbru31** [comment]
Can you please post your server.log when using the dev build?

**Comment by KillauraHacks** [comment]
https://pastebin.com/2TwHuSxX

**Comment by timbru31** [comment]
Sorry not gonna help people who use cracked plugins.
