### ISSUE TITLE
Explosion-chance separate options

### ISSUE THREAD

**Issue by baticag** [timbru31/SilkSpawners#108]
Can you separate config options for creeper-explosion chance and tnt-explosion chance?
Thank you in advance!

**Comment by timbru31** [comment]
Hi @baticag, 

thanks for the suggestion, I'll take a look.

**Comment by baticag** [comment]
Hey mate,

Any news about this?

**Comment by timbru31** [comment]
Thanks for your reminder @baticag - sadly I had no spare time for plugin development in the last few weeks. I'm hopefully able to spend some time this weekend towards SilkSpawners development.

**Comment by timbru31** [comment]
This is a dupe of #67 - closing this one.
