### ISSUE TITLE
Any spawner placed, turns to pig, and if broken it turns to pig as well.

### ISSUE THREAD

**Issue by v1t0man36658** [timbru31/SilkSpawners#117]
**## What steps will reproduce the problem?**
So, upon deleting MyPets, it allowed SS to work. Now, when I do /ss give {name} Cow 1, it'll say given a cow spawner, and the spawner you're holding says Cow spawner, upon placing it down, it turns into a Pig spawner. What I noticed, is that if you right click that pig spawner with any mob egg, it'll turn into whatever mob egg you right clicked it, and from therefore on behaving NORMALLY like it should, UNTIL you break it, once you break the spawner to pick it up, it still says your desired mob name until you place it down again.
**## Expected output**
Should be showing up as my desired mob WITHOUT having to use an egg everytime, and WITHOUT it turning to pig unpon placing/breaking.
**## What do you see instead?**
Turns to pig after you placed the spawner that clearly said it was a different mob. 
**## Log file of the issue/error**
Screenshots provided:
http://prntscr.com/ij7dgz
http://prntscr.com/ij7dsg
http://prntscr.com/ij7dwg
I used the egg here ^
http://prntscr.com/ij7e43
http://prntscr.com/ij7e99
Upon placing it down again, it turns to pig.

**## /version output?**
http://prntscr.com/ij7flu

**## SilkSpawners version**
Silk Spawners 5.0.0

**## Please provide any additional information below.**
Screenshots already provided. MyPets was removed, as that wasnt letting SilkSpawners work. Running the following plugins, see link below:
http://prntscr.com/ij7g1f
**## Checklist**

- [ X] I am aware that issues caused by /reload are ignored
- [ X] If there is a (potential) plugin conflict, I've identified the conflicting plugin
- [ X] I have added a valid /version output
- [ X] I have added a valid SilkSpawners version
- [ X] I have attached necessary information like a screenshot, my list of plugins, config or permissions file(s)

**Comment by timbru31** [comment]
I'm cleaning up old issues. If this issue still persists, please comment here and I'll re-open this issue.
