### ISSUE TITLE
Ocelot Spawners Bug

### ISSUE THREAD

**Issue by NotAHackedCookie** [timbru31/SilkSpawners#119]
## What steps will reproduce the problem?
Placing a Ocelot spawner in nether or end.
## Expected output
Ocelots spawning.
## What do you see instead?
Ocelots don't spawn.
## /version output?
git-PaperSpigot-"8b18730" (MC:1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)

## SilkSpawners version
5.0.0

## Please provide any additional information below.
- Plugins List: https://pastebin.com/1a2bF6M3
## Checklist

- [x] I am aware that issues caused by /reload are ignored
- [X] If there is a (potential) plugin conflict, I've identified the conflicting plugin
- [X] I have added a valid /version output
- [X] I have added a valid SilkSpawners version
- [X] I have attached necessary information like a screenshot, my list of plugins, config or permissions file(s)

**Comment by timbru31** [comment]
SilkSpawners does not alter spawning criteria and looking at the Minecraft wiki Ocelot's are having these criteria:
> Ocelot: In Jungle Biomes, on Grass or leaf blocks that are above sea level, any light level.

Obviously The End or Nether do not contain grass ;)
