### ISSUE TITLE
ChestShop + SilkSpawners stacking unstackable

### ISSUE THREAD

**Issue by baticag** [timbru31/SilkSpawners#123]
Spawners that are bought from ChestShop appeard stacked even if in configuration of SilkSpawners plugin, unstackable option is set to true:

Should spawners be unstackable
spawnersUnstackable: true

Referenced from:
https://github.com/ChestShop-authors/ChestShop-3/issues/116

**Comment by baticag** [comment]
Any news about this problem?

**Comment by timbru31** [comment]
No, PRs welcome. I have very little time for OSS and don't play Minecraft anymore.

**Comment by timbru31** [comment]
If the issue persists, please open a new issue.
