### ISSUE TITLE
SilkSpawner only Pig spawner

### ISSUE THREAD

**Issue by hacalios** [timbru31/SilkSpawners#124]
## What steps will reproduce the problem?
i use command /ss give [myname] cow 1 and when i place on the floor it's spawn a pig spawner only . the other spawners commands same that
## Expected output
A pig spawner only
## What do you see instead?
Just only the pig spawners for every give commands
## Log file of the issue/error
did't have error on console
## /version output?
1.8.8

## SilkSpawners version
newest version 5.0.0

## Checklist

- [x ] I am aware that issues caused by /reload are ignored
- [x ] If there is a (potential) plugin conflict, I've identified the conflicting plugin
- [x ] I have added a valid /version output
- [ x] I have added a valid SilkSpawners version
- [x] I have attached necessary information like a screenshot, my list of plugins, config or permissions file(s)
![2018-04-17_17 22 12](https://user-images.githubusercontent.com/29684509/38864139-f77007d8-4263-11e8-875c-5f60816326a7.png)
![image](https://user-images.githubusercontent.com/29684509/38864176-11ebc89a-4264-11e8-9c30-46f2f48f7ace.png)

![image](https://user-images.githubusercontent.com/29684509/38864182-17a2f06a-4264-11e8-89c4-e4edd905b633.png)

Config Files
https://hastebin.com/izeyojupeg.bash

**Comment by timbru31** [comment]
No support for cracked plugin users.
