### ISSUE TITLE
I can't place down spawners.

### ISSUE THREAD

**Issue by Liam134** [timbru31/SilkSpawners#125]
## What steps will reproduce the problem?
Placing down the spawner
## Expected output
The spawner places as its supposed to
## What do you see instead?
It gives me an error saying Placing default spawner (either this spawner is invalid or disabled)
![3](https://user-images.githubusercontent.com/12987748/39087970-cd335150-45a1-11e8-9fbe-ae218abea44a.PNG)
## Log file of the issue/error
None
## /version output?
1.12

## SilkSpawners version
v5.0.0

## Please provide any additional information below.
It places down the spawner but it puts a default one and not the one mined
## Checklist

- [x] I am aware that issues caused by /reload are ignored
- [x] If there is a (potential) plugin conflict, I've identified the conflicting plugin
- [ ] I have added a valid /version output
- [x] I have added a valid SilkSpawners version
- [x] I have attached necessary information like a screenshot, my list of plugins, config or permissions file(s)
![capture](https://user-images.githubusercontent.com/12987748/39087981-f7f5fbcc-45a1-11e8-9f0e-eeb23482f152.PNG)
![capture2](https://user-images.githubusercontent.com/12987748/39087982-f9453a4c-45a1-11e8-93bf-4963216164cc.PNG)

**Comment by timbru31** [comment]
Where did you obtain the spawner from?

**Comment by Liam134** [comment]
I mined it down

**Comment by Liam134** [comment]
@timbru31 I mined it out of a mineshaft

**Comment by timbru31** [comment]
I'm cleaning up old issues. If this issue still persists, please comment here and I'll re-open this issue.
