### ISSUE TITLE
Maven all messed up

### ISSUE THREAD

**Issue by pablo67340** [timbru31/SilkSpawners#130]
## What steps will reproduce the problem?
Building project via maven using depency
## Expected output
Completed artifact

## What do you see instead?
[ERROR] Failed to execute goal on project GUIShop: Could not resolve dependencies for project com.pablo67340.GUIShop:GUIShop:jar:6.4.0: Failed to collect dependencies at de.dustplanet:SilkSpawners:jar:5.1.0-SNAPSHOT -> com.sk89q:worldguard:jar:6.2.1:

## SilkSpawners version

5.1.0

## Please provide any additional information below.
POM: https://pastebin.com/T5UjbtKH

**Comment by timbru31** [comment]
Please try this exclusion: https://stackoverflow.com/a/7556707/1902598.  
A `mvn clean install -X` log would be good, too. Otherwise it's nearly impossible to help with no further error messages.

**Comment by pablo67340** [comment]
Oh wow! Ahahah, that worked flawlessly! Thanks for your help!

Also, I'd like to remind you to update the Maven information on the dev bukkit page. I believe it still points to 4.0.0. 

Thanks for your help!

P.S I also appreciate the Issue you opened a while ago on GUIShop's repo warning of deprecated methods. Helps a ton!

**Comment by timbru31** [comment]
> Also, I'd like to remind you to update the Maven information on the dev bukkit page. I believe it still points to 4.0.0.

yeah a little (overall) spring cleanup is really necessary for this project. 😇
