### ISSUE TITLE
Failed to load SilkSpawners on startup with default config

### ISSUE THREAD

**Issue by RainOfPain125** [timbru31/SilkSpawners#131]
## What steps will reproduce the problem?
Using default config, not sure.
## Expected output
> no bugs
## What do you see instead?
https://pastebin.com/QRap8MC2
## Log file of the issue/error
https://pastebin.com/QRap8MC2
## /version output?

git-Paper-1416 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)

Plugins: 
ActionAnnouncer, AdvancedBan, ArrowTrails, Auctions, AutoRestart, BlowableObsidians, BountyHunters, CFD, ChatFeelings, ChatInjector, ChestRestock, ColoredAnvils, CombatLogX, CompatNoCheatPlus, ConditionalCommands, CoreProtect, CrazyCrates, CrazyEnchantments, CrazyEnvoy, DeluxeJoin, DiscordSRV, EasyBackup, EpicRename, Essentials, EssentialsChat, eZProtector, FactionChat, Factions, FastAsyncWorldEdit, GuiRedeemMCMMO, GUIShop, HeadDrop, HolographicDisplays, InfoBook, InventoryFull, LuckPerms, MassiveBooks, MassiveCore, mcMMO, MessageAnnouncer, Multiverse-Core, NoCheatPlus, NoPlugins, OCMFixer, OpenInv, PerWorldInventory, PlaceholderAPI, Plan, PluginLibrary, ProtocolLib, ServerListPlus, ShulkerBlock, SilkSpawners, SuperTrails, SuperVanish, Tablist, TitleManager, Trading, Vault, VPNGuard, Wild, WorldBorder, WorldEdit, WorldGuard

## SilkSpawners version
 SilkSpawners v5.0.2

## Please provide any additional information below.
N/A
## Checklist

- [X] I am aware that issues caused by /reload are ignored
- [ ] If there is a (potential) plugin conflict, I've identified the conflicting plugin
- [X] I have added a valid /version output
- [X] I have added a valid SilkSpawners version
- [X] I have attached necessary information like a screenshot, my list of plugins, config or permissions file(s)

**Comment by timbru31** [comment]
Please delete the SilkSpawners folder once and restart your server.
