### ISSUE TITLE
Server lag allows duping spawners

### ISSUE THREAD

**Issue by Devillion** [timbru31/SilkSpawners#133]
## What steps will reproduce the problem?
When the player has some lag (like block lag) when they break the spawner it will sometimes get placed in their inventory and stay on the ground letting them break it again.

## Expected output
duped spawners

## Log file of the issue/error
there are no errors when this happens

## /version output?
https://i.imgur.com/XCvUlyK.png

## SilkSpawners version
It's #470 on your dev builds I think, the latest one. It doesn't have any version numbers listed on your dev page.

## Checklist

- [ ] I am aware that issues caused by /reload are ignored
- [ ] If there is a (potential) plugin conflict, I've identified the conflicting plugin
- [ ] I have added a valid /version output
- [ ] I have added a valid SilkSpawners version
- [ ] I have attached necessary information like a screenshot, my list of plugins, config or permissions file(s)

**Comment by Devillion** [comment]
We found another issue. Using the Wurst hacked client with the fast break setting will allow you to dupe spawners. If you stop mining the spawner before it breaks it will give you extra spawners.

**Comment by timbru31** [comment]
v6.0.1 has been released. If this issue persists, please create a new one. Thanks!
