### ISSUE TITLE
Silk Spawner in kits

### ISSUE THREAD

**Issue by AdvancedGP** [timbru31/SilkSpawners#150]
## What steps will reproduce the problem?
have any spawner in your inventory, do /kitcreate spawner 1, then do /kit spawner
## Expected output
Gaining whatever spawner i added into the kit
## What do you see instead?
pig spawner (name of spawner is still the actual mob though
## Log file of the issue/error
none
## /version output?
Spigot 1.12.2 R0.1 SNAPSHOT -- CraftBukit git-Spigot-2086bb0-d0a3620

## SilkSpawners version
SilkSspawners 5.0.2 

## Please provide any additional information below.
I am using essentialsX kits, is there a specific kit plugin that works with silkspawner sapwners?
## Checklist

- [x] I am aware that issues caused by /reload are ignored
- [ ] If there is a (potential) plugin conflict, I've identified the conflicting plugin
- [x] I have added a valid /version output
- [x] I have added a valid SilkSpawners version
- [ ] I have attached necessary information like a screenshot, my list of plugins, config or permissions file(s)

**Comment by timbru31** [comment]
Since I'm not playing Minecraft anymore, I'm not up to date with kit plugins.

For Essentials kits you can give them a lore which will be recognized by SilkSpawners (see http://ess.khhq.net/wiki/Command_Reference/Kits)
