### ISSUE TITLE
cant get or place cave_spider, blaze works

### ISSUE THREAD

**Issue by freakyy85** [timbru31/SilkSpawners#151]
## What steps will reproduce the problem?
a player can place and mine blaze spawners but not silk spawners and as far as i can tell the permission for just cave_spider isnt revoked from the rank?
## Expected output
player should be able to mine cave_spider and also place
## Log file of the issue/error
none
## /version output?
[Sat, 25. Aug 2018 14:08:02 CEST INFO] This server is running CraftBukkit version git-Spigot-fe3ab0d-82f4b3b (MC: 1.13) (Implementing API version 1.13-R0.1-SNAPSHOT)

## SilkSpawners version
b486

## Checklist

- [x] I am aware that issues caused by /reload are ignored
- [x] If there is a (potential) plugin conflict, I've identified the conflicting plugin
- [x] I have added a valid /version output
- [x] I have added a valid SilkSpawners version
- [x] I have attached necessary information like a screenshot, my list of plugins, config or permissions file(s)

**Comment by timbru31** [comment]
Thanks, I’ll check if the permissions have changed in the refactoring.

**Comment by timbru31** [comment]
The permission node has not changed and is: cavespider

**Comment by freakyy85** [comment]
well i gave them the * permission node. for all mobs. but cavespider spawner doesnt work.

**Comment by timbru31** [comment]
Giving 
```
- silkspawners.place.*
- silkspawners.silkdrop.*
```
works fine for me

**Comment by freakyy85** [comment]
strange ... hm ... i will check later today, if the problem persists ill write u. but i dont think ive done it wrong as there are no specific permission nodes and other spawners work. 1.13 no worldguard support enabled.
