### ISSUE TITLE
Giant Spawners wont work 1.12.2

### ISSUE THREAD

**Issue by FaZz129** [timbru31/SilkSpawners#153]
## What steps will reproduce the problem?
Placing a giant spawner with /ss give {name} giant and placing it
## Expected output
To spawn giant zombies
## What do you see instead?
It just sits there with the normal zombie entity inside the spawner and does nothing
## /version output?
CraftBukkit version git-Spitgot-642f6d2-57ab4cf (MC1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)

## SilkSpawners version
5.0.2

## Please provide any additional information below.
My players cant use the spawners when they buy them and i cant either when i spawn them. I checked the mobs.yml and they are enabled in there
## Checklist

- [x] I am aware that issues caused by /reload are ignored
- [x] If there is a (potential) plugin conflict, I've identified the conflicting plugin
- [x] I have added a valid /version output
- [x] I have added a valid SilkSpawners version
- [x] I have attached necessary information like a screenshot, my list of plugins, config or permissions file(s)
[SilkSpawners.zip](https://github.com/timbru31/SilkSpawners/files/2330183/SilkSpawners.zip)

**Comment by timbru31** [comment]
Spawning behavior is not altered by SilkSpawners. They don't spawn naturally.
The following criteria have to be met: `Light >11 AND <8 - Conditions can't be met in vanilla` (see https://minecraft.gamepedia.com/Giant)
