### ISSUE TITLE
1.13.1 issue with spawners

### ISSUE THREAD

**Issue by Sikatsu** [timbru31/SilkSpawners#155]
## What steps will reproduce the problem?
Mine a zombie pig spawner will give a normal pig spawner back
## Expected output
It should give a zombie pig spawner instead.
## What do you see instead?
A pig spawner is given

## /version output?
This server is running CraftBukkit version git-Spigot-2440e18-6304ccd (MC: 1.13.1) (Implementing API version 1.13.1-R0.1-SNAPSHOT)

## SilkSpawners version
6.0.0-Snapshot

## Checklist

- [x] I am aware that issues caused by /reload are ignored
- [x] If there is a (potential) plugin conflict, I've identified the conflicting plugin
- [x] I have added a valid /version output
- [x] I have added a valid SilkSpawners version
- [x] I have attached necessary information like a screenshot, my list of plugins, config or permissions file(s)

**Comment by timbru31** [comment]
Where did you obtain the spawner from? If mined naturally, is your world a freshly generated or have you upgraded (if yes from which version?)

**Comment by Sikatsu** [comment]
I added it as a vote reward. It runs an essentialsX command to give the spawner. So it gets placed and once it gets mined it'll become a pig spawner. Fresh 1.13 world.

**Comment by timbru31** [comment]
Please try /ss give instead. It might be esssentials that’s broken, too.
I‘m going to take a look anyway

**Comment by Sikatsu** [comment]
I used /ss give before, but changed it to an essentials command since i'm not sure till what point SilkSpawners supports 1.13+

Might indeed be essentials too, though.
Also, this might happen with more spawners but I only give out a pigman spawner.

**Comment by Sikatsu** [comment]
It also seems players are able to convert spawners again with eggs, even tho I disabled that. 1.13 issue?

**Comment by Sikatsu** [comment]
Using /ss give has the same issue. Pigman spawners change into pig spawners.

**Comment by timbru31** [comment]
@Sikatsu have you (or can you try) tried other mobs? Are those effected, too?

**Comment by Sikatsu** [comment]
I don't hear anyone about having issues with the LEGAL mob spawners when they mine and place them. Only the one from the vote chest which is an illegal one.

**Comment by Sikatsu** [comment]
Found out this was an issue with essentials. It has been fixed using the experimental branch for 1.13.

Closing this issue.

**Comment by timbru31** [comment]
Awesome, thanks for letting me know.
