### ISSUE TITLE
[1.13+] Change spawners with eggs can't be disabled anymore

### ISSUE THREAD

**Issue by Sikatsu** [timbru31/SilkSpawners#157]
In 1.12.2 we were able to disable the function to change spawners with eggs. In 1.13+ they are free to do that again. Could you fix this so they don't abuse this system?

**Comment by Sikatsu** [comment]
@timbru31 Hey, any news on this? Kinda important feature for me to work.

**Comment by Jay9519** [comment]
they are probably ignoring this issue report as it doesn't have any plugin information

**Comment by Permanently** [comment]
@Jay9519 that's a bit of a wild accusation, they could just be busy.

Still, I'd quite like this fixed as well.

**Comment by timbru31** [comment]
Busy is the better term; and “they” means one person.  
My spare time towards plugin development is sadly quite limited and I’m sure for the delay. On the other hand nobody offered their help so far or made any Pull Requests to complete 1.13 support.

**Comment by Permanently** [comment]
Gotta use "they", don't wanna assume genders amirite ;)

**Comment by timbru31** [comment]
Please open a new issue if the problem persists, egg handling  is improved in the recent commits.
