### ISSUE TITLE
SilkSpawners problem

### ISSUE THREAD

**Issue by NoopyyGaming** [timbru31/SilkSpawners#158]
### What steps will reproduce the problem?

The command /ss change make a error into the console, and the /ss give NoopyyGaming Zombie 1 is not working
### Expected output

It should give a spawner that i want to change, and it should me a zombie spawner too
### What do you see instead?

![error](https://user-images.githubusercontent.com/33123515/45095968-aed38380-b11f-11e8-90f6-3fd454c1effe.PNG)

Nothing is doing right
### /version output?

This server is running CraftBukkit version git-Spigot-d20369f-7fc5cd8 (MC: 1.9) (Implementing API version 1.9-R0.1-SNAPSHOT)
### SilkSpawners version

6.0.0-Snapshot
### Checklist

- [x] - I am aware that issues caused by /reload are ignored
- [x] - If there is a (potential) plugin conflict, I've identified the conflicting plugin
- [x] - I have added a valid /version output
- [x] - I have added a valid SilkSpawners version
- [x] - I have attached necessary information like a screenshot, my list of plugins, config or permissions file(s)

**Comment by timbru31** [comment]
For the meantime please use 5.0.2 for Minecraft < 1.13, also your report is missing a valid SilkSpawners version

**Comment by NoopyyGaming** [comment]
Okey and what about the Skipping entity with id, i only get this when i use /ss give to give myself a spawner and then place it, but when i change ths spawner to another mob, this message don't appear, so it mean that's not the fault of EsentialsX

**Comment by timbru31** [comment]
It's still caused by EssentialsX, try to remove it, test again and see that the message is gone.
