### ISSUE TITLE
SpawnerShop Support Error

### ISSUE THREAD

**Issue by BenTheNoble** [timbru31/SilkSpawners#159]
## What steps will reproduce the problem?
Put SilkSpawners.jar and ShopGUIPlus.jar in the same plugins folder

## Expected output
Both plugins will throw an error and disable

## What do you see instead?
Both plugins throw an error and disable

## Log file of the issue/error
https://hastebin.com/xunemetije.md

## /version output?
This server is running CraftBukkit version git-PaperSpigot-"4c7641d" (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)

## SilkSpawners version
5.0.2

## Please provide any additional information below.
https://imgur.com/a/fWLyvz8

## Checklist

- [x] I am aware that issues caused by /reload are ignored
- [x] If there is a (potential) plugin conflict, I've identified the conflicting plugin
- [x] I have added a valid /version output
- [x] I have added a valid SilkSpawners version
- [x] I have attached necessary information like a screenshot, my list of plugins, config or permissions file(s)

**Comment by BenTheNoble** [comment]
UPDATE:
https://www.spigotmc.org/resources/factions-top-1-7-1-12-f-top-factionsuuid-savagefactions.20661/ 

When I removed that plugin, it started working.

**Comment by timbru31** [comment]
Thanks for letting me know.
