### ISSUE TITLE
Crafting ingredient amount

### ISSUE THREAD

**Issue by NoChanceSD** [timbru31/SilkSpawners#16]
Hi, i'm not sure if this is possible (at least without reflection) but would be nice to be able to set the ingredient amount of a recipe.
Example: 'B,DIRT,2'
Which would take 2 dirt in the recipe. I will search later if there's a way to do this but i'm suggesting it here anyway.

**Comment by timbru31** [comment]
Hi,

I'm not aware of any way to do this (so far). I'm neither aware of any recipe in Vanilla MC that needs an ingredient X times. If you have any further information like NMS code, please tell me :smile:

**Comment by timbru31** [comment]
@NoChanceSD Had you time to take a closer look?

**Comment by NoChanceSD** [comment]
No, i didn't look into this yet but i think it should be possible.
