### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by DarkFort** [timbru31/SilkSpawners#160]
![screenshot_2](https://user-images.githubusercontent.com/25278617/45363813-24889500-b5e1-11e8-95f2-cd1a66a89ffc.png)
PaperSpigot 1.12.2
Latest version SilkSpawners

**Comment by timbru31** [comment]
Use 5.0.2 for 1.12.X builds.

**Comment by timbru31** [comment]
This is fixed in master.
