### ISSUE TITLE
Mob spawners change with eggs

### ISSUE THREAD

**Issue by sackboylbp** [timbru31/SilkSpawners#167]
## What steps will reproduce the problem?
If you click a spawner with an egg you can change the spawner to that type, even if you don't have permission to do so. silkspawners.changetypewithegg.* permission node is negated but players can still change it.

## Expected output
Expected for players to not be able to change spawner types with eggs.

## What do you see instead?
Players changing spawner type with eggs.

## Log file of the issue/error
No error in log/console

## /version output?
This server is running Paper version git-Paper-318 (MC: 1.13.1) (Implementing API version 1.13.1-R0.1-SNAPSHOT)

## SilkSpawners version
SilkSpawners v6.0.0-SNAPSHOT-b491

## Please provide any additional information below.
Plugins: BetterRTP*, BuycraftX*, ChestShop, ClueScrolls, Coins*, ConsoleScheduler*, CoreProtect, CrateReloaded, DeluxeMenus*, DeluxeTags*, EnjinMinecraftPlugin*, Essentials*, EssentialsChat*, EssentialsSpawn*, GriefPrevention, GroupManager*, HolographicDisplays, Jobs, LiteBans, Lottery*, Marriage*, mcMMO, MessageAnnouncer*, MyCommand*, PlaceholderAPI, PlayerVaults, ProtocolLib*, PvPToggle*, Rankup, React*, SilkSpawners, SuperbVote, TAB, TimeIsMoney*, Vault*, Votifier, WorldEdit, WorldGuard

## Checklist

- [X] I am aware that issues caused by /reload are ignored
- [X] If there is a (potential) plugin conflict, I've identified the conflicting plugin
- [X] I have added a valid /version output
- [X] I have added a valid SilkSpawners version
- [X] I have attached necessary information like a screenshot, my list of plugins, config or permissions file(s)

**Comment by Jay9519** [comment]
any update on this issue?

**Comment by Jay9519** [comment]
Is this plugin abandoned?

**Comment by timbru31** [comment]
Please try a newer build, egg handling is improved in the recent commits.
