### ISSUE TITLE
Issue with Gettings a Spawners Type.

### ISSUE THREAD

**Issue by Savag3life** [timbru31/SilkSpawners#168]
## What steps will reproduce the problem?
https://gyazo.com/c5c8490f1f6cb5353d9f6a9b9e42291b

When placing a spawner with spigots BlockPlaceEvent, or SilkSpawners SilkSpawnerSSpawnerPlaceEvent,

You cannot get a spawners type, 

        String entityID = su.getSpawnerEntityID(e.getBlock());
        String name = su.getCreatureName(entityID);

Will Always return pig.

## Expected output
Spawner Type (IronGolem, ...)
## What do you see instead?
Pig
## Log file of the issue/error
Null
## /version output?
This server is running CraftBukkit version git-TacoSpigot-c98afce0 (MC: 1.8.8) (Implementing API version 1.8.8-R0.2-SNAPSHOT) (BeerSpigot)

## SilkSpawners version
5.0.2

## Please provide any additional information below.
Not sure if you need to check NBT tags for the spawner type now, or if the wiki is out of date, but the javadoc is also offline now.
## Checklist

- [x] I am aware that issues caused by /reload are ignored
- [x] If there is a (potential) plugin conflict, I've identified the conflicting plugin
- [x] I have added a valid /version output
- [x] I have added a valid SilkSpawners version
- [x] I have attached necessary information like a screenshot, my list of plugins, config or permissions file(s)

**Comment by timbru31** [comment]
1.8.8 works fine for me.
