### ISSUE TITLE
Spawners not unstacking many are destroyed.

### ISSUE THREAD

**Issue by Gnoarn** [timbru31/SilkSpawners#169]
## What steps will reproduce the problem?
Enabling MergedSpawners
## Expected output
Sometimes spawners are destroyed instead of dropped with 100 drop chance
## What do you see instead?
spawners being broken not dropped
## Log file of the issue/error
there is no stacktrace
## /version output?
using git-Paper-355 1.13.1-R0.1-SNAPSHOT
also does just the same with git-Spigot-f6a273b-8ab46ff 1.13.1

## SilkSpawners version
using silkspawners 6 b491

## Checklist

- [X] I am aware that issues caused by /reload are ignored
- [X] If there is a (potential) plugin conflict, I've identified the conflicting plugin
- [X] I have added a valid /version output
- [X] I have added a valid SilkSpawners version
- [X] I have attached necessary information like a screenshot, my list of plugins, config or permissions file(s)

**Comment by timbru31** [comment]
v6.0.1 has been released. If this issue persists, please create a new one. Thanks!
