### ISSUE TITLE
Problem with Placing Spawners

### ISSUE THREAD

**Issue by justin2001** [timbru31/SilkSpawners#17]
When I buy and place a spawner without changing my spawner to another hotkey, it has no problem. If I change it to another hotkey and place it, it disappeared!
Here is the proof:
https://www.youtube.com/watch?v=OL6FndS9yaw

**Comment by timbru31** [comment]
Thanks for the report, I've confirmed this in creative, however **not in survival**.

Does this happen when you are in survival, too?

(MC Client 1.8.7, SS 3.6.6, Spigot git-Spigot-f928e7a-e91aed8)

**Comment by justin2001** [comment]
Nope.

**Comment by timbru31** [comment]
I've tested this in Vanilla, and it does occur too. I'll open a bug on spigot later.

Von meinem iPhone gesendet

**Comment by justin2001** [comment]
Thanks so much!

**Comment by timbru31** [comment]
Bug report still pending.
Happens with git-Spigot-c8a0d06-58d972f (MC: 1.8.7), too

**Comment by timbru31** [comment]
Bug report opened:
https://hub.spigotmc.org/jira/browse/SPIGOT-1065

**Comment by justin2001** [comment]
Thanks!

**Comment by timbru31** [comment]
Spigot issue was closed via the comment
"This isn't a spigot bug. From what I know, it's a Mojang 'feature'."

There is nothing I can do about it, sorry.

**Comment by justin2001** [comment]
Thanks.
