### ISSUE TITLE
"disableChangeTypeWithEgg" Configuration not working.

### ISSUE THREAD

**Issue by Wekylend** [timbru31/SilkSpawners#175]
## Expected output
No output.
## What do you see instead?
The opposite of what this configuration option is supposed to do.

## SilkSpawners version
v5.0.0-5.0.2 (latest version atm) are the versions I've tried and had the same issues.

## Please provide any additional information below.
I've configured SilkSpawners to disable spawner changing with eggs via the following configuration section:

disableChangeTypeWithEgg: true

I took a peak at the source code (https://github.com/timbru31/SilkSpawners/blob/master/modules/SilkSpawners/src/main/java/de/dustplanet/silkspawners/listeners/SilkSpawnersPlayerListener.java) and I've located the issue  (line 89)
## Checklist

- [x] I am aware that issues caused by /reload are ignored
- [x] If there is a (potential) plugin conflict, I've identified the conflicting plugin
- [ ] I have added a valid /version output
- [x] I have added a valid SilkSpawners version
- [x] I have attached necessary information like a screenshot, my list of plugins, config or permissions file(s)

**Comment by Sifress96** [comment]
i have the same problem too
but i can't find a fix

**Comment by timbru31** [comment]
Logic has been refactored with https://github.com/timbru31/SilkSpawners/commit/812d6c3641d99b0956ff89fd3e45955309ececd2
