### ISSUE TITLE
updete more information SilkSpawners do not change

### ISSUE THREAD

**Issue by REVIEWGAMINGMAN** [timbru31/SilkSpawners#179]
## What steps will reproduce the problem?
doing test is on a test server
## Log file of the issue/error
https://pastebin.com/irbajtpD
## Checklist

- [x] I am aware that issues caused by /reload are ignored
- [x] If there is a (potential) plugin conflict, I've identified the conflicting plugin
- [x] I have added a valid /version output
- [CB 1.7.9-R0.1 ] I have added a valid SilkSpawners version
- [ EssentialsChat vPre2.14.1.3 GroupManager vPre2.14.1.3 FINAL] I have attached necessary information like a screenshot, my list of plugins, config or permissions file(s)

**Comment by timbru31** [comment]
You are using SilkSpawners v3.5, this version **> 4 years old!**. Please upgrade to SilkSpawners v5.0.2 and report any other issues.
