### ISSUE TITLE
Mob Eggs can be Changed with /SS Change

### ISSUE THREAD

**Issue by Disorbs** [timbru31/SilkSpawners#184]
## What steps will reproduce the problem?
/ss change <mob> while holding a mob egg
## Expected output
for it not to work since i have no permission for it only silkspawners.changetype.<mob> and silkdrop/place
## What do you see instead?
it switches the mob egg to any mob available 
## /version output?
Paper spigot 1.12.2 #1592

## SilkSpawners version
5.0.2

**Comment by timbru31** [comment]
Please show me your permission files. Does the feature work as intended when you run only SilkSpawners on a server? If yes, then another plugin is conflicting.

**Comment by Disorbs** [comment]
Here is my permissions for donors+Defaults - https://pastebin.com/raw/AtKMU8s0

ill come back here to let you know whether or not its a conflict

**Comment by Disorbs** [comment]
anything?

**Comment by Disorbs** [comment]
anything?

**Comment by timbru31** [comment]
Please try v6.0.0, if the issue persists, open a new one please.
