### ISSUE TITLE
Error when trying to run commands. 

### ISSUE THREAD

**Issue by TheCanadian529** [timbru31/SilkSpawners#188]
## What steps will reproduce the problem?
/ss - Or any ss command

## Expected output
any ss command
## What do you see instead?
Error in console
## Log file of the issue/error
https://pastebin.com/4LzwrwiK
## /version output?
1.13.2 Latest Spigot Unsure of how to get what you want.

## SilkSpawners version
 SilkSpawners v5.0.2 --1.5

## Checklist

- [x] I am aware that issues caused by /reload are ignored
- [x] If there is a (potential) plugin conflict, I've identified the conflicting plugin
- [ ] I have added a valid /version output
- [x] I have added a valid SilkSpawners version
- [x] I have attached necessary information like a screenshot, my list of plugins, config or permissions file(s)

**Comment by timbru31** [comment]
1.13 is not yet supported

**Comment by TheCanadian529** [comment]
Well shit, Any ETA for 1.13 support?
