### ISSUE TITLE
minetinker silktouch conflicts with silkspawners

### ISSUE THREAD

**Issue by madolebr** [timbru31/SilkSpawners#192]
## What steps will reproduce the problem?
install minetinker plugin with silkspawners, disable silktouch through silkspawners, but allow it through minetinker. mine a spawner which will result in the name being in italic, and when placed, it turns into a pig spawner.

## Expected output
normal mob spawner placement without it being replaced by a pig spawner

## What do you see instead?
pigs spawning where i just mined the zombie spawner from using silktouch modifier in minetinker plugin

## Log file of the issue/error
no errors

## /version output?
 This server is running Paper version git-Paper-563 (MC:1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)

## SilkSpawners version
6.0.0 dev 503

## Please provide any additional information below.
i know the issue is caused due to silkspawners not registering the name, so it registers it as an invalid entity. just hoping for compatability to be made, as currently i have no way to disable people from just changing spawners with eggs, or even renaming them on an anvil, so this is my best hope
## Checklist

- [x] I am aware that issues caused by /reload are ignored
- [x] If there is a (potential) plugin conflict, I've identified the conflicting plugin
- [x] I have added a valid /version output
- [x] I have added a valid SilkSpawners version
- [x] I have attached necessary information like a screenshot, my list of plugins, config or permissions file(s)

**Comment by timbru31** [comment]
v6.0.1 has been released. If this issue persists, please create a new one. Thanks!
