### ISSUE TITLE
Illager Eggs and BossShopPro

### ISSUE THREAD

**Issue by Trenly** [timbru31/SilkSpawners#194]
## What steps will reproduce the problem?
I am using BossShopPro to sell monster eggs. BossShopPro uses the monsteregg:MONSTER_TYPE tag to give an egg in conjunction with the SilkSpawners plugin.
Eggs effected by issue:
monsteregg:Evoker
monsteregg:Vindicator

## Expected output
I expect to see the proper egg displayed in the shop display. 

## What do you see instead?
Instead I see blank eggs. This only effects the Illager Eggs. Other eggs such as Parrot, Husk, Vex, Stray, and Polar Bear work without issue. When using the eggs as a reward from the shop, all eggs are valid except the Illager Eggs, which are given as blank eggs.

## Log file of the issue/error
No error message given; No log file generated;

## /version output?
This server is running Paper version git-Paper-1399 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)

## SilkSpawners version
v5.0.2

## Please provide any additional information below.
Plugins List: BossShopPro, ConsoleInGame, Essentials, EssentialsChat, FastAsyncWorldEdit, GuiShopManager, MobArena, OldCombatMechanics, PermissionsEx, PlaceholderAPI, PluginsBaker, ServerSigns, SilkSpawners, Vault, ViaBackwards, ViaRewind, ViaVersion, VoxelSniper, Worldedit, WorldGuard

Possible other plugins in question: BossShopPro with GuiShopManager add in

View my [mobs.yml](https://pastebin.com/mUGWucn4)
View my [config.yml](https://pastebin.com/mMPuNx2y)

## Checklist

- [x] I am aware that issues caused by /reload are ignored
- [ ] If there is a (potential) plugin conflict, I've identified the conflicting plugin
- [x] I have added a valid /version output
- [x] I have added a valid SilkSpawners version
- [x] I have attached necessary information like a screenshot, my list of plugins, config or permissions file(s)

**Comment by timbru31** [comment]
v6.0.1 has been released. If this issue persists, please create a new one. Thanks!
