### ISSUE TITLE
What is the permission for evoker?

### ISSUE THREAD

**Issue by andrewkm** [timbru31/SilkSpawners#196]
The spigot resource page tells us to go here:
https://dev.bukkit.org/projects/silkspawners/pages/permissions

But this page doesn't have evoker.
Is there an updated list of permissions somewhere.

Reason I ask is because stuff like pigzombie is zombiepigman in permissions, and seeings as an evoker is evocation_illager, im not sure which to use in permissions.

Is there an updated list?

**Comment by timbru31** [comment]
Thanks for the hunt, I’ll update the wiki page.
