### ISSUE TITLE
SilkSpawners Error On Startup

### ISSUE THREAD

**Issue by Sean1472** [timbru31/SilkSpawners#202]
## What steps will reproduce the problem?
Turning the server on

## Expected output
The plugin still works in-game despite it saying "disabled" in console?!

## What do you see instead?
Crashes with ShopGUI+ and MergedSpawner
## Log file of the issue/error
Easier read: https://pastebin.com/e171iL4k
`12.05 13:24:36 [Server] INFO WorldGuard was found and support is enabled
12.05 13:24:36 [Server] WARN Loading MergedSpawner v12.0.9-RC3java.lang.ClassNotFoundException: de.dustplanet.silkspawners.compat.null.NMSHandler
12.05 13:24:36 [Server] WARN at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
12.05 13:24:36 [Server] WARN at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:156)
12.05 13:24:36 [Server] WARN at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:104)
12.05 13:24:36 [Server] WARN at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
12.05 13:24:36 [Server] WARN at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
12.05 13:24:36 [Server] WARN at java.lang.Class.forName0(Native Method)
12.05 13:24:36 [Server] WARN at java.lang.Class.forName(Class.java:264)
12.05 13:24:36 [Server] WARN at de.dustplanet.util.SilkUtil.setupNMSProvider(SilkUtil.java:150)
12.05 13:24:36 [Server] WARN at de.dustplanet.util.SilkUtil.<init>(SilkUtil.java:122)
12.05 13:24:36 [Server] WARN at net.brcdev.shopgui.provider.spawner.SpawnerSilkSpawnersProvider.hook(SpawnerSilkSpawnersProvider.java:16)
12.05 13:24:36 [Server] WARN at net.brcdev.shopgui.ShopGuiPlugin.setupSpawners(ShopGuiPlugin.java:325)
12.05 13:24:36 [Server] WARN at net.brcdev.shopgui.ShopGuiPlugin.onEnable(ShopGuiPlugin.java:143)
12.05 13:24:36 [Server] WARN at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
12.05 13:24:36 [Server] WARN at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316)
12.05 13:24:36 [Server] WARN at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
12.05 13:24:36 [Server] WARN at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:395)
12.05 13:24:36 [Server] WARN at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:344)
12.05 13:24:36 [Server] WARN at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:442)
12.05 13:24:36 [Server] WARN at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:403)
12.05 13:24:36 [Server] WARN at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:341)
12.05 13:24:36 [Server] WARN at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:289)
12.05 13:24:36 [Server] WARN at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616)
12.05 13:24:36 [Server] WARN at java.lang.Thread.run(Thread.java:748)
12.05 13:24:36 [Server] ERROR Could not find support for this CraftBukkit version.
12.05 13:24:36 [Server] INFO Check for updates at https://dev.bukkit.org/projects/silkspawners/
12.05 13:24:36 [Server] INFO Disabling SilkSpawners now!
12.05 13:24:36 [Server] INFO SilkSpawners support enabled.
12.05 13:24:36 [Server] ERROR Error occurred while enabling ShopGUIPlus v1.19.1 (Is it up to date?)
12.05 13:24:36 [Server] INFO java.lang.NullPointerException: null
12.05 13:24:36 [Server] INFO at de.dustplanet.util.SilkUtil.newSpawnerItem(SilkUtil.java:411) ~[?:?]
12.05 13:24:36 [Server] INFO at net.brcdev.shopgui.provider.spawner.SpawnerSilkSpawnersProvider.getSpawnerItem(SpawnerSilkSpawnersProvider.java:25) ~[?:?]
12.05 13:24:36 [Server] INFO at net.brcdev.shopgui.util.ItemUtils.loadItemStackFromConfig(ItemUtils.java:92) ~[?:?]
12.05 13:24:36 [Server] INFO at net.brcdev.shopgui.shop.ShopManager.loadShops(ShopManager.java:192) ~[?:?]
12.05 13:24:36 [Server] INFO at net.brcdev.shopgui.ShopGuiPlugin.load(ShopGuiPlugin.java:192) ~[?:?]
12.05 13:24:36 [Server] INFO at net.brcdev.shopgui.ShopGuiPlugin.onEnable(ShopGuiPlugin.java:146) ~[?:?]
12.05 13:24:36 [Server] INFO at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[custom.jar:git-Paper-1613]
12.05 13:24:36 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316) ~[custom.jar:git-Paper-1613]
12.05 13:24:36 [Server] INFO at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) ~[custom.jar:git-Paper-1613]
12.05 13:24:36 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:395) ~[custom.jar:git-Paper-1613]
12.05 13:24:36 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:344) ~[custom.jar:git-Paper-1613]
12.05 13:24:36 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:442) ~[custom.jar:git-Paper-1613]
12.05 13:24:36 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:403) ~[custom.jar:git-Paper-1613]
12.05 13:24:36 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:341) ~[custom.jar:git-Paper-1613]
12.05 13:24:36 [Server] INFO at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:289) ~[custom.jar:git-Paper-1613]
12.05 13:24:37 [Multicraft] Skipped 5 lines due to rate limit (60/s)
12.05 13:24:37 [Server] INFO EntityTypes version: 1_12
12.05 13:24:38 [Server] INFO WorldGuard was found and support is enabled
12.05 13:24:38 [Server] WARN Enabling MergedSpawner v12.0.9-RC3[MS] Event listener for 'Look to inspect' registered.java.lang.ClassNotFoundException: de.dustplanet.silkspawners.compat.null.NMSHandler
12.05 13:24:38 [Server] WARN at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
12.05 13:24:38 [Server] WARN at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:156)
12.05 13:24:38 [Server] WARN at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:104)
12.05 13:24:38 [Server] WARN at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
12.05 13:24:38 [Server] WARN at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
12.05 13:24:38 [Server] WARN at java.lang.Class.forName0(Native Method)
12.05 13:24:38 [Server] WARN at java.lang.Class.forName(Class.java:264)
12.05 13:24:38 [Server] WARN at de.dustplanet.util.SilkUtil.setupNMSProvider(SilkUtil.java:150)
12.05 13:24:38 [Server] WARN at de.dustplanet.util.SilkUtil.<init>(SilkUtil.java:122)
12.05 13:24:38 [Server] WARN at com.vk2gpz.mergedspawner.a.d.a(d.java:58)
12.05 13:24:38 [Server] WARN at com.vk2gpz.mergedspawner.a.d.<init>(d.java:53)
12.05 13:24:38 [Server] WARN at com.vk2gpz.mergedspawner.g.a(g.java:337)
12.05 13:24:38 [Server] WARN at com.vk2gpz.mergedspawner.c.e.h.a.<init>(a.java:28)
12.05 13:24:38 [Server] WARN at com.vk2gpz.mergedspawner.g.<init>(g.java:200)
12.05 13:24:38 [Server] WARN at com.vk2gpz.mergedspawner.MergedSpawner.onEnable(MergedSpawner.java:60)
12.05 13:24:38 [Server] WARN at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
12.05 13:24:38 [Server] WARN at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316)
12.05 13:24:38 [Server] WARN at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
12.05 13:24:38 [Server] WARN at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:395)
12.05 13:24:38 [Server] WARN at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:344)
12.05 13:24:38 [Server] WARN at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:442)
12.05 13:24:38 [Server] WARN at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:403)
12.05 13:24:38 [Server] WARN at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:341)
12.05 13:24:38 [Server] WARN at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:289)
12.05 13:24:38 [Server] WARN at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616)
12.05 13:24:38 [Server] WARN at java.lang.Thread.run(Thread.java:748)
12.05 13:24:38 [Server] ERROR Could not find support for this CraftBukkit version.
12.05 13:24:38 [Server] INFO Check for updates at https://dev.bukkit.org/projects/silkspawners/
12.05 13:24:38 [Server] INFO Disabling SilkSpawners now!`
## /version output?
Paper version git-Paper-1613 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)

## SilkSpawners version
Version 5.0.2

## Please provide any additional information below.
Plugin list:
ActionAPI, AdvancedGambler, AdvanedOreGen, AnimatedNames, AntiJigsaw, AntiPortalTrapping, ArmorStandEditor, ASkyblock, AtherialPlayTime, Battlepass, BeautyIndicator, BlockCommand, BlockGlitchFIX, BlockParticles, BuycraftX, Chestshop, Citizens, Clearlag, CombatTagPlus, CommandNPC, CommandRegions, CoreProtect, CrazyAuctions, CrazyCrates, CrazyEnchantments, Credits2Cash, CubeMiniatures, DeluxeMenus, DeluxeTags, EpicChatPrefix, EpicRename, Essentials, EssentialsChat, EssentialsProtect, EssentialsSpawn, FastAsyncWorldEdit, Featherboard, HeadDatabase, HLR, HolographicDisplays, HolographicExtension, HopperLimits, Images, Infotools, IslandBorder, IslandTop, ItemFrameTagger, JetsSellChests, KillStats, KitsPreview, Litebans, Luckperms, MC-Cron, mcMMO, MergedSpawner, MessageAnnouncer, Minions, MonthlyCrates, MoreVaultPlus, Multiverse-Core, MVdWPlaceholderAPI, NightVisionPLUS, NoFlyZone, NoWeather, oGolemDrops, OtherDrops, PlaceHolderAPI, ProtocolLib, ProtocolSupport, RandomLocation, RepairTokens, SellStick, ServerListPlus, ShopGUIPLUS, Showitem, Silkspawners, Spartan, StackMob, SuperBoosters, SuperDonations, SuperMobCoins, SuperPouches, Tab, TtleManager, TradeMe, Vault, Viaversion, VoidSpawn, VoidWorld, Votifier, VotingPlugin, Vouchers, WithdrawX, WorldBorder, WorldEdit, WorldGuard, WorldRestorer

## Checklist

I have the latest 5.0.2 silkspawners
I have the latest MergedSpawners (12.0.10-RC3)
I have the latest ShopGUIPlus (1.19.1-SNAPSHOT)

I am doing full restarts, not /reload
I've tested each plugin 1 by 1 and still doesn't work.

**Comment by Sean1472** [comment]
EDIT: New error showed up
`[20:05:29] [Server thread/INFO]: [SilkSpawners] Loading support for v1_12_R1
[20:05:29] [Server thread/ERROR]: [SilkSpawners] Failed to dump entity map: Class de.dustplanet.silkspawners.compat.v1_12_R1.NMSHandler can not access a member of class net.minecraft.server.v1_12_R1.EntityTypes with modifiers "private static final"
[20:05:29] [Server thread/WARN]: java.lang.IllegalAccessException: Class de.dustplanet.silkspawners.compat.v1_12_R1.NMSHandler can not access a member of class net.minecraft.server.v1_12_R1.EntityTypes with modifiers "private static final"
[20:05:29] [Server thread/WARN]: 	at sun.reflect.Reflection.ensureMemberAccess(Unknown Source)
[20:05:29] [Server thread/WARN]: 	at java.lang.reflect.AccessibleObject.slowCheckMemberAccess(Unknown Source)
[20:05:29] [Server thread/WARN]: 	at java.lang.reflect.AccessibleObject.checkAccess(Unknown Source)
[20:05:29] [Server thread/WARN]: 	at java.lang.reflect.Field.get(Unknown Source)
[20:05:29] [Server thread/WARN]: 	at de.dustplanet.silkspawners.compat.v1_12_R1.NMSHandler.rawEntityMap(NMSHandler.java:80)
[20:05:29] [Server thread/WARN]: 	at de.dustplanet.util.SilkUtil.scanEntityMap(SilkUtil.java:598)
[20:05:29] [Server thread/WARN]: 	at de.dustplanet.util.SilkUtil.load(SilkUtil.java:167)
[20:05:29] [Server thread/WARN]: 	at de.dustplanet.util.SilkUtil.<init>(SilkUtil.java:107)
[20:05:29] [Server thread/WARN]: 	at net.brcdev.shopgui.provider.spawner.SpawnerSilkSpawnersProvider.hook(SpawnerSilkSpawnersProvider.java:16)
[20:05:29] [Server thread/WARN]: 	at net.brcdev.shopgui.ShopGuiPlugin.setupSpawners(ShopGuiPlugin.java:325)
[20:05:29] [Server thread/WARN]: 	at net.brcdev.shopgui.ShopGuiPlugin.onEnable(ShopGuiPlugin.java:143)
[20:05:29] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[20:05:29] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337)
[20:05:29] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403)
[20:05:29] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:381)
[20:05:29] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:330)
[20:05:29] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:422)
[20:05:29] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:383)
[20:05:29] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:338)
[20:05:29] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272)
[20:05:29] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545)
[20:05:29] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)`

**Comment by timbru31** [comment]
Could you please check if the server correctly start when you remove MergedSpawners and ShopGUI+?

**Comment by timbru31** [comment]
Alternatively make sure to upgrade MergedSpawner, this one is outdated.

**Comment by Sean1472** [comment]
Thanks for the reply. Upon further testing, I removed the depends in the plugin.yml and it loaded perfectly. I'm unsure of why this happened though?

**Comment by timbru31** [comment]
From which plugin.yml did you remove the depends?

**Comment by Sean1472** [comment]
Silkspawners

**Comment by timbru31** [comment]
If that works fine in your case, great!
I'm going to close this issue since the current master has been fixed to ensure SilkSpawners does load first (https://github.com/timbru31/SilkSpawners/commit/33f4038394dbdeeb5d384610f4701c2069b75b74)
