### ISSUE TITLE
Spawners cannot be placed or mined with silk touch

### ISSUE THREAD

**Issue by Klawdek** [timbru31/SilkSpawners#203]
## What steps will reproduce the problem?
Place a spawner or mine a spawner with silk touch
## Expected output
That the placed spawner is placed with the mob that it is.  That the spawner that is mined with silk touch will drop itself.
## What do you see instead?
Placed spawners turn to pigs.  Silk Touch mined spawners drop nothing.

## Log file of the issue/error
No error given
## SilkSpawners version

SilkSpawners version 6.0.0-SNAPSHOT-b503
CraftBukkit version git-Spigot-1a3504a-dfa7583 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)
## Checklist

- [ ] I am aware that issues caused by /reload are ignored
- [ ] If there is a (potential) plugin conflict, I've identified the conflicting plugin
- [ ] I have added a valid /version output
- [ ] I have added a valid SilkSpawners version
- [ ] I have attached necessary information like a screenshot, my list of plugins, config or permissions file(s)

**Comment by BrettplayMC** [comment]
Same here.

**Comment by BrettplayMC** [comment]
It has something to do with the NBT.  The SilkSpawners spawner has 3 NBT while when mined it has 1...

**Comment by pat-p** [comment]
Was also experiencing this on our end. The auto updater took us from 5.0.2 to 6.0.0, once that happened, players with permission "silkspawners.silkdrop.*" do not have spawners drop when using Silk Touch. It also switches our spawners to Pigs when changing servers throughout the network. So, I believe this is 6.0.0 exclusive. We have downgraded to 5.0.2 and it's working as intended.

**Comment by timbru31** [comment]
Without your help I’m unable to debug this. This sounds like a plugin conflict.

The issue is missing required version information and the information where spawners are obtained from?

**Comment by pat-p** [comment]
I was just verifying that this report is indeed an issue. 
Was using the same version as the report stated, 6.0.0.
My server version is "Paper version git-Paper-d43da9f (MC: 1.12.1) (Implementing API version 1.12.1-R0.1-SNAPSHOT)"

We do have some plugins that use other spawners. So, they were not obtained through SilkSpawners, however SilkSpawners is used to drop them and our custom Mob Spawner plugin does the actual spawning. So, turning a normal "Endermite" spawner to a custom one which have endermites that drop different loot. Granted, we hooked into the SilkSpawners to make it work back on the older version, so maybe you updated something on your side in 6.0.0 where the old hooks have changed. So, possibly is an issue that is caused in combination with one of our other plugins, but once we go back down to 5.0.2, it worked just as intended like before.
Even when placing a normal Endermite spawner that isn't spawning one of our custom mobs, it just doesn't drop when broken with Silk Touch. 

Was just more so trying to verify that this is an issue others are seeing though and that it should be looked into, if you need any more info or want any additional testing from me, feel free to let me know.

**Comment by timbru31** [comment]
Permissions weren't altered in 6.0.0 - but WorldGuard support was updated to WorldGuard v7 API. Can you check your setting of `useWorldGuard`?

Besides that, an NBT tag output would be good to debug why spawners spawn only pigs. (you could either upload a `.dat` file from a player holding it in the inventory [found in the world/playerdata folder] or use Minecrafts built in NBT viewer: https://gaming.stackexchange.com/a/248017/250395 or e.g., PowerNBT plugin)

**Comment by vletalle** [comment]
https://pastebin.com/1fNWL8ca
i have also the same issues :(

**Comment by timbru31** [comment]
> https://pastebin.com/1fNWL8ca
> i have also the same issues :(

That is something completely different. Please use the search, the issue is already fixed.

**Comment by kC0pter** [comment]
I have the same issue.
Running a bukkit server with only silkspawner and dynmap plugin.
Only OPs can silktouch spawners or get xp from broken spawner.
Non-OP doesn't get any of those 2 things.
No permission changes have been made.

**Comment by timbru31** [comment]
>  Running a bukkit server with only silkspawner and dynmap plugin.
Again, this is **NOT** specific. Only a valid /version output helps.

> Only OPs can silktouch spawners or get xp from broken spawner.
> Non-OP doesn't get any of those 2 things.

If you have no permissions plugin installed, this is expected. 

> No permission changes have been made.

Your statement is inconsistent - do you have a permissions plugin installed or not?

**Comment by MarcusRai** [comment]
Olá, gostaria de relatar um bug que está acontecendo comigo, adicionei as permissões corretamente, mas o grupo "membro" pode apenas quebrar o reprodutor, mas não posso colocá-lo, apenas com "Op" o reprodutor em o grupo admin funciona bem, no entanto, no grupo membro, só é possível quebrá-lo.

**Comment by MarcusRai** [comment]
Hello, I would like to report a bug that is happening to me, I added the permissions all right, but the "member" group can only break the spawner, but I can't put it, only with "Op" the spawner in the admin group works well , however, in the member group it is only possible to break it.

**Comment by timbru31** [comment]
Share your permissions file with the names of the players that do not work correctly. Otherwise I can’t help

**Comment by TNTUP** [comment]
Can confirm this. Somehow spawners are being returned as "minecraft:blaze" and I'm using LuckPerms and it registers permission like "silkspawners.place.minecraft:blaze which should be blaze instead... Plugin is quite unusable for now, players are losing their spawners

**Comment by timbru31** [comment]
Closing due to lack of feedback. Without a proper step-by-step reproduction example I can't help. 99% of the time another plugin is causing conflicts with SilkSpawners. I can only recommend to disable each plugin one by one until the culprit is found and SilkSpawners works again.
