### ISSUE TITLE
[Feature request] Restrict silking spawners to certain tools

### ISSUE THREAD

**Issue by HunterGPlays** [timbru31/SilkSpawners#21]
Is there a way where you could make only certain tools with silk touch work for picking up spawners? I want to make sure people can only use a hoe with silk touch on it to pick up the spawner.

**Comment by timbru31** [comment]
Currently all tools with at least SilkTouch level >= 1 (default) should be able to mine spawners.
Does your enchanted hoe work currently?

(Line in SilkUtil:
https://github.com/timbru31/SilkSpawners/blob/master/src/main/java/de/dustplanet/util/SilkUtil.java#L802
)

**Comment by HunterGPlays** [comment]
I meant to ask if you could add in the ability to restrict picking up spawners to certain tools such as: only allowing hoes with silk touch to pick up spawners, not just any tool with silk touch.

**Comment by timbru31** [comment]
Alright, then I have understood you right.
I guess a config option should be possible.

**Comment by timbru31** [comment]
Hi.

I've added this option in build 303: http://ci.dustplanet.de/job/SilkSpawners/303/
You can configure the tools in the "allowedTools" section in the config.yml.

If the feature works as intended, please close the issue. :)

**Comment by HunterGPlays** [comment]
Works as intended.
