### ISSUE TITLE
Giving spawner to offline player

### ISSUE THREAD

**Issue by MrDsa1** [timbru31/SilkSpawners#213]
## What steps will reproduce the problem?
I have an auto donate site and there is a spanner purchase service. The problem is that after buying spawner - the rcon console performs command - /silkspawner give {user} spider 1

## Expected output
Give spawner to a player even if he is not online.

## What do you see instead?
Since the player is not online, the spawner cannot be given.

## Log file of the issue/error
It is not an error.

## /version output?

This server is running CraftBukkit version git-Spigot-dcd1643-e60fc34 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
This is a final build for 1.12.2. Please see https://www.spigotmc.org/ for details about upgrading.

## SilkSpawners version

SilkSpawners v5. 0. 2
## Please provide any additional information below.
Is it possible to somehow solve this problem? For example, to give a spawner to a player when he entering the server or something else, a solution is very necessary.

## Checklist

- [+] I am aware that issues caused by /reload are ignored
- [+] If there is a (potential) plugin conflict, I've identified the conflicting plugin
- [+] I have added a valid /version output
- [+] I have added a valid SilkSpawners version
- [+] I have attached necessary information like a screenshot, my list of plugins, config or permissions file(s)

P.s Sorry for bad English

**Comment by timbru31** [comment]
Certainly possible, but not yet supported: https://github.com/timbru31/SilkSpawners/issues/126.

Thanks for following the issue template, I'm actually going to close the old issue in favor of this one!

**Comment by timbru31** [comment]
This will be in the next release. Requires online mode support for the UUID lookup.
