### ISSUE TITLE
Impossible to apply it for a custom pickaxe

### ISSUE THREAD

**Issue by jules62100** [timbru31/SilkSpawners#219]
## What steps will reproduce the problem?
I’m in 1.12 and it’s impossible to choose a custom pickaxe (form customitem) to pick spawner
## Checklist

- [ ] I am aware that issues caused by /reload are ignored
- [ ] If there is a (potential) plugin conflict, I've identified the conflicting plugin
- [ ] I have added a valid /version output
- [ ] I have added a valid SilkSpawners version
- [ ] I have attached necessary information like a screenshot, my list of plugins, config or permissions file(s)

**Comment by timbru31** [comment]
Thanks a lot for your issue, however the issue template exists for a reason. 😊   
It helps us to debug the issue further and to provide a solution much faster. With important information missing, we unfortunately can't help you.

Therefore, please edit this issue accordingly or close and create a new one and make sure to provide all the required information.
