### ISSUE TITLE
Crafting permission also prevents buying spawners from custom villagers

### ISSUE THREAD

**Issue by blablubbabc** [timbru31/SilkSpawners#22]
https://github.com/timbru31/SilkSpawners/blob/master/src/main/java/de/dustplanet/silkspawners/listeners/SilkSpawnersInventoryListener.java#L63

This line only checks if the clicked slot is of type RESULT. However, other types of inventories have a result slot as well, like furnaces and villager trading windows (any maybe other inventory types as well).

This currently prevents not only crafting of spawners, but also trading (with customly setup villager trades).

**Comment by timbru31** [comment]
This should be fixed via https://github.com/timbru31/SilkSpawners/commit/5107300b912d197a375d6b12e55fa1a086dbf9de

Can you verify and close?
(Dev builds are here: https://ci.dustplanet.de/job/SilkSpawners)

Sorry for the delay in fixing this :/

**Comment by blablubbabc** [comment]
This should work fine now.
