### ISSUE TITLE
SilkSpawners & CrazyEnchantments issue

### ISSUE THREAD

**Issue by NoopyyGaming** [timbru31/SilkSpawners#222]
## What steps will reproduce the problem?
I don't know, no steps will do it.

## Expected output
/

## What do you see instead?
Nothing is write instead

## Log file of the issue/error
[latest.log](https://github.com/timbru31/SilkSpawners/files/4331871/latest.log)

## /version output?
This server is running CarftBukkit version git-PaperSpigot-"4c7641d" (MC. 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)

## SilkSpawners version
SilkSpawners v5.0.2

## Please provide any additional information below.
It says that the plugin doesn't found an class : de.dustplanet.silkspawners.compat.null.NMSHandler
My Plugins list: [Plugins](https://gyazo.com/766ba426a182d4a9a72a4084af0c7939)

## Checklist

- [x] I am aware that issues caused by /reload are ignored
- [x] If there is a (potential) plugin conflict, I've identified the conflicting plugin
- [x] I have added a valid /version output
- [x] I have added a valid SilkSpawners version
- [x] I have attached necessary information like a screenshot, my list of plugins, config or permissions file(s)

**Comment by timbru31** [comment]
v6.0.1 has been released. If this issue persists, please create a new one. Thanks!
