### ISSUE TITLE
Version 6.0.0 cause duplicate spawner

### ISSUE THREAD

**Issue by tomatoshiba** [timbru31/SilkSpawners#224]
## What steps will reproduce the problem?
Place a spawner fast and break it will drop 2 spawners of that type instead 1
## Log file of the issue/error
Dont have
## SilkSpawners version

6.0.0

## Checklist

- [x] I am aware that issues caused by /reload are ignored
- [ ] If there is a (potential) plugin conflict, I've identified the conflicting plugin
- [x] I have added a valid /version output
- [x] I have added a valid SilkSpawners version
- [ ] I have attached necessary information like a screenshot, my list of plugins, config or permissions file(s)

**Comment by timbru31** [comment]
Quoting my template:

> Please note that _WITHOUT_ the specific version output your issue _WILL BE IGNORED_

>A /version output looks like this: This server is running CraftBukkit version git-Spigot-06f33d0-86fdf92 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)

> Adding e.g. only 1.12.2 will lead _IGNORED ISSUES_
