### ISSUE TITLE
Place and break errors in v6.0.0 on 1.8.8

### ISSUE THREAD

**Issue by TheRAPT3X** [timbru31/SilkSpawners#225]
https://pastebin.com/734MdDqc

https://pastebin.com/CSDUCy3e

**Comment by timbru31** [comment]
Disable WorldGuard support or install it:

> Caused by: java.lang.NoClassDefFoundError: com/sk89q/worldguard/WorldGuard

**Comment by timbru31** [comment]
Pardon, this was indeed an error with WorldGuard v6. Either use https://ci.dustplanet.de/job/SilkSpawners/54/ or wait until I'll release 6.0.1 soon.
