### ISSUE TITLE
Quickly placing spawners will duplicate them

### ISSUE THREAD

**Issue by AfkF24** [timbru31/SilkSpawners#226]
## What steps will reproduce the problem?
Quickly place multiple spawners. Eventually you'll see that they aren't being taken from your inventory but are still being placed.

## /version output
This server is running Paper version git-Paper-227 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)

## SilkSpawners version
6.0.0

## Checklist

- [x] I am aware that issues caused by /reload are ignored
- [ ] If there is a (potential) plugin conflict, I've identified the conflicting plugin
- [x] I have added a valid /version output
- [x] I have added a valid SilkSpawners version
- [ ] I have attached necessary information like a screenshot, my list of plugins, config or permissions file(s)

**Comment by timbru31** [comment]
Is this reproducible on a server running on SilkSpawners as the plugin?

**Comment by AfkF24** [comment]
> Is this reproducible on a server running on SilkSpawners as the plugin?

Will test soon

**Comment by timbru31** [comment]
My findings show that this might be caused by EssentialsX - can you confirm that the dupe bug is not happening when EssentialsX is disabled?

**Comment by timbru31** [comment]
Please try this EssentialsX build:
[EssentialsX-2.17.2.69.jar.zip](https://github.com/timbru31/SilkSpawners/files/4558554/EssentialsX-2.17.2.69.jar.zip)

**Comment by AfkF24** [comment]
Yup, running SilkSpawners on a clean server doesn't have that issue. I've tested the Essentials version you've attached and it seems to be fixed.

**Comment by timbru31** [comment]
Thanks for the report, I believe I've identified the real root cause.

**Comment by timbru31** [comment]
Could you please try this build: https://ci.dustplanet.de/job/SilkSpawners/52/ with the original EssentialsX version, not my patch?

**Comment by AfkF24** [comment]
> Could you please try this build: https://ci.dustplanet.de/job/SilkSpawners/52/ with the original EssentialsX version, not my patch?

Just tried it out, seems to be working great!

**Comment by timbru31** [comment]
Great, thanks for the feedback. Expect an official 6.0.1 soon.
