### ISSUE TITLE
Iron_Golem is not recognised but IronGolem is - breaking ShopGUIPlus

### ISSUE THREAD

**Issue by Lewes** [timbru31/SilkSpawners#229]
## What steps will reproduce the problem?

1. Type /ss give <username> irongolem
It will give you a normal functioning iron golem spawner.
2. Type /ss give <username> iron_golem
It will say that iron_golem is not recognised (even though this is the EntityType).

## Expected output

iron_golem should be valid because it is used in ShopGUIPlus to give the spawner.

## What do you see instead?

Covered in steps to reproduce.

## Log file of the issue/error

No log, but got a photo.

https://i.imgur.com/MDoN4Ot.png

## /version output?

1.8.8-R0.2-SNAPSHOT. PaperSpigot. Build version is useless as we have small modifications (completely unrelated to entities).

## SilkSpawners version

SilkSpawners: 6.0.1-SNAPSHOT-b54
ShopGUI Version: 1.28.0
ShopGUISilkSpawnersBridge: 1.1.2

## Please provide any additional information below.

mobs.yml: https://hastebin.com/tubonudiro.bash

## Checklist

- [x] I am aware that issues caused by /reload are ignored
- [x] If there is a (potential) plugin conflict, I've identified the conflicting plugin
- [x] I have added a valid /version output
- [x] I have added a valid SilkSpawners version
- [x] I have attached necessary information like a screenshot, my list of plugins, config or permissions file(s)

**Comment by timbru31** [comment]
Can you delete your `mobs.yml` once when your server is off? The next start should generate a fresh one - `iron_golem` works fine for me on my test server.

**Comment by timbru31** [comment]
Nevermind my comment please, I see you are on 1.8.8.

**Comment by timbru31** [comment]
`[00:29:38] [Server thread/INFO]: [SilkSpawners] Entity VillagerGolem = IRON_GOLEM[interface org.bukkit.entity.IronGolem] (display name: Iron Golem, aliases: [iron_golem, ironman, iron, irongolem, villagergolem, ig, igolem])
`

Now all aliases and internal ID's should be detected again, please try: https://ci.dustplanet.de/job/SilkSpawners/57/
