### ISSUE TITLE
Spawners Appear Empty

### ISSUE THREAD

**Issue by spoopybean** [timbru31/SilkSpawners#234]
## What steps will reproduce the problem?
You could join my server in-progress and see for yourself if you'd like. I'm not sure.
## Expected output
Expected to have mobs spawn out of the corresponding spawner.
## What do you see instead?
A zombie spawner that turns instantly into an empty spawner...
## Log file of the issue/error
None.
## /version output?
This server is running CraftBukkit version git-Spigot-db6de12-18fbb24 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)
21.05 11:11:52 [Server] INFO You are 1912 version(s) behind

Silkspawners 6.1.0

## SilkSpawners version
`Plugins (69): TreasurePets, PlaceholderAPI, WithdrawPlus, PlugMan, TnTFill, ChatReaction, InfiniteDispensersAndDroppers, Quests, MobCoins, TagsGUI, ViaVersion, HideStream, AsyncWorldEditInjector, CoreProtect, ChatControl, MessageAnnouncer, BuycraftX, JellyLegs, Votifier, Multiverse-Core, ProtocolLib, NoCheatPlus, GuiRedeemMCMMO, BlowableObsidians, MVdWPlaceholderAPI, NoPoppyDrop, AsyncWorldEdit, Vouchers, PermissionsEx, mcMMO, CustomCrates, MotdManager-Reloaded, VyzonUtils, GAListener, Vault, SellChest, BlastJackpot, Rankup, HolographicDisplays, VoteParty, AuctionHouse, ChestCommands, PlayerVaults, GenBuckets, WorldEdit, Essentials, AnimatedNames, LiteBans, Citizens, EssentialsChat, CrazyEnvoy, WorldGuard, CoinFlip, Factions, ServerSigns, CommandNPC, EssentialsSpawn, MonthlyCrates, TitleManager, CombatLog, FBasics, LinkItem, CustomBosses, SilkSpawners, MergedMob, React, NoFlyZone, ShopGUIPlus, CrazyEnchantments`

## Checklist

- [x] I am aware that issues caused by /reload are ignored
- [x] If there is a (potential) plugin conflict, I've identified the conflicting plugin
- [x] I have added a valid /version output
- [x] I have added a valid SilkSpawners version
- [x] I have attached necessary information like a screenshot, my list of plugins, config or permissions file(s)

**Comment by timbru31** [comment]
Please try https://ci.dustplanet.de/job/SilkSpawners/86/
