### ISSUE TITLE
Build failed (not authorized for dustplanet)

### ISSUE THREAD

**Issue by spommerening** [timbru31/SilkSpawners#239]
Hi, any change I can build the package locally myself? 

```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 6.211 s
[INFO] Finished at: 2020-06-01T11:33:47+02:00
[INFO] Final Memory: 21M/183M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project silkspawners-v1_8_R1: Could not resolve dependencies for project de.dustplanet:silkspawners-v1_8_R1:jar:6.1.1-SNAPSHOT: Failed to collect dependencies at org.bukkit:craftbukkit:jar:1.8-R0.1-SNAPSHOT: Failed to read artifact descriptor for org.bukkit:craftbukkit:jar:1.8-R0.1-SNAPSHOT: Could not transfer artifact org.bukkit:craftbukkit:pom:1.8-R0.1-SNAPSHOT from/to dustplanet (https://repo.dustplanet.de/artifactory/private): Not authorized , ReasonPhrase:Unauthorized. -> [Help 1]
```

**Comment by timbru31** [comment]
Quoting my answer from Discord:

> SilkSpawners requires the CraftBukkit jar files as dependencies for compilation of the version specific code (known as NMS, too) - due to the DMCA of CraftBukkit from 2014 (https://github.com/github/dmca/blob/master/2014/2014-09-05-CraftBukkit.md) one is no longer allowed to distribute those binaries (that's why you need to run BuildTools all the time and not just download the newest spigot.jar)

> Because of the DMCA the artifacts are hosted in a private repo of my Artifactory server and only my Jenkins has access to it.
You'll need to run BuildTools for each version of Minecraft - this will populate your local Maven repository, too. That might be enough to build, otherwise, if the artifacts are present, you can remove the https://repo.dustplanet.de/artifactory/private repository entry from the pom(s)

> But yes, it's a shame that it's so difficult to compile SilkSpawners yourself. I'll keep this as a reminder to add some instructions to the readme file.

**Comment by spommerening** [comment]
Thank you!

**Comment by timbru31** [comment]
Btw the README has been updated in #240
