### ISSUE TITLE
Spawners appear empty (Minecraft 1.8 SilkSpawners 6.1.0)

### ISSUE THREAD

**Issue by e2trunade** [timbru31/SilkSpawners#246]
## What steps will reproduce the problem?
The issue occurs whenever I place a spawner so placing a spawner in minecraft 1.8 with version 6.1.0 should have the same result

## Expected output
A Blaze spawner
## What do you see instead?
an empty spawner
## Log file of the issue/error
[latest.log](https://github.com/timbru31/SilkSpawners/files/4787799/latest.log)

## /version output?
This server is running CraftBukkit version git-Spigot-21fe707-e1ebe52 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)

## SilkSpawners version
6.1.0

## Checklist

- [x] I am aware that issues caused by /reload are ignored
- [x] If there is a (potential) plugin conflict, I've identified the conflicting plugin
- [x] I have added a valid /version output
- [x] I have added a valid SilkSpawners version
- [x] I have attached necessary information like a screenshot, my list of plugins, config or permissions file(s)

**Comment by timbru31** [comment]
Fixed in the latest dev builds: https://ci.dustplanet.de/job/SilkSpawners/lastSuccessfulBuild/artifact/modules/SilkSpawners/target/SilkSpawners.jar - release will be uploaded soon to BukkitDev and SpigotMC
