### ISSUE TITLE
Netherite Pickaxe does not silk spawners

### ISSUE THREAD

**Issue by HorusApl** [timbru31/SilkSpawners#258]
## What steps will reproduce the problem?
Enchant Netherite Pickaxe with Silk Touch
## Expected output
Get a spawner
## What do you see instead?
Don't get a spawner
## Log file of the issue/error
N/A
## /version output?
This server is running Paper version git-Paper-34 (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT)
Previous version: git-Paper-26 (MC: 1.16.1)

## SilkSpawners version
6.3.1

## Checklist

- [X] I am aware that issues caused by /reload are ignored
- [X] If there is a (potential) plugin conflict, I've identified the conflicting plugin
- [X] I have added a valid /version output
- [X] I have added a valid SilkSpawners version
- [X] I have attached necessary information like a screenshot, my list of plugins, config or permissions file(s)

**Comment by timbru31** [comment]
This was fixed by f16c66cc2d86c427cb7243076e3219be6d29b843, please add it your config manually.
