### ISSUE TITLE
Named Netherite Pickaxe Problem

### ISSUE THREAD

**Issue by DumplingSaint** [timbru31/SilkSpawners#261]
## What steps will reproduce the problem?
Give players permission to mine spawners with a silk touch pick but not permission for nosilk. Then mine the spawner with a silk touch netherite pick.
## Expected output
Spawner drops.
## What do you see instead?
No spawner drops.
## /version output?
This server is running Paper version git-Paper-101 (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT)
22.07 13:21:19 [Server] INFO Checking version, please wait...
22.07 13:21:19 [Server] INFO Previous version: git-Paper-100 (MC: 1.16.1)

## SilkSpawners version
v6.3.1

## Please provide any additional information below.
Plugins: https://gyazo.com/a774cf542b5762e6e4905b7d414a914b
 A renamed diamond pick works perfectly fine, and so does a netherite pick when nosilk is enabled.
The pick tested is named "Silky pogaxe"

## Checklist

- [x] I am aware that issues caused by /reload are ignored
- [x] If there is a (potential) plugin conflict, I've identified the conflicting plugin
- [x] I have added a valid /version output
- [x] I have added a valid SilkSpawners version
- [x] I have attached necessary information like a screenshot, my list of plugins, config or permissions file(s)

**Comment by timbru31** [comment]
Have you added the pickaxe to the allowed tools section in your config.yml?

**Comment by timbru31** [comment]
Closing due to lack of feedback.
