### ISSUE TITLE
Netherite Pickaxes do not seem to work.

### ISSUE THREAD

**Issue by HittmanA** [timbru31/SilkSpawners#267]
## What steps will reproduce the problem?
New SilkSpawners install. Give permissions for dropping a spawner with silktouch, then attempt to mine with a silktouch enchanted netherite pickaxe. No drop.
## Expected output
A spawner dropping.
## What do you see instead?
No spawner dropping, just breaking.
## Log file of the issue/error
NA
## /version output?
This server is running Paper version git-Paper-131 (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT)

## SilkSpawners version
6.3.1

## Please provide any additional information below.

I tested this issue with a diamond, gold, iron, and wood pickaxe. All drop the spawner if they have silktouch. I have also tried adding NETHERITE_PICKAXE to the allowed tools config portion, and it still doesn't work.

## Checklist

- [x] I am aware that issues caused by /reload are ignored
- [x] If there is a (potential) plugin conflict, I've identified the conflicting plugin
- [x] I have added a valid /version output
- [x] I have added a valid SilkSpawners version
- [x] I have attached necessary information like a screenshot, my list of plugins, config or permissions file(s)

**Comment by timbru31** [comment]
Have you restarted your server after adding the pickaxe? If yes, please enable verboseConfig, restart again, mine a spawner and post the log output.

**Comment by HittmanA** [comment]
I tested restarting the server and it appears to work perfectly now. Before I had been doing /silkspawner reload, which I was under the impression would reload the entire config. Seems to be resolved now!
