### ISSUE TITLE
Enderman not spawn

### ISSUE THREAD

**Issue by TheKlimoT** [timbru31/SilkSpawners#279]
SilkSpawner - 6.4.0
Core: This server is running Yatopia version git-Yatopia-"c832092" (MC: 1.16.3) (Implementing API version 1.16.3-R0.1-SNAPSHOT)

Enderman don't starting spawns

Spawner clean

![изображение](https://user-images.githubusercontent.com/26817853/95692338-bd10f980-0c2d-11eb-8261-92ecb263ea8b.png)

**Comment by timbru31** [comment]
SilkSpawners does not alter spawning behavior or criteria. It’s probably your stacker plugin.
