### ISSUE TITLE
Default localization.yml broken

### ISSUE THREAD

**Issue by AntZaro** [timbru31/SilkSpawners#28]
I just downloaded this plugin on a small test server. The server had no issues at all before installation, and has very few plugins installed to begin with. 

During the server startup, the following errors appear: 
http://pastebin.com/WMmyP4pL

I am currently using a different spawner plugin on the main server, but it seems to be throwing entity errors. Since I saw SilkSpawners was updated so recently for 1.9.4, I thought there wouldn't be any errors like that. However, I still encountered these issues.

**Comment by timbru31** [comment]
Can you please pastebin your localization.yml, too?

**Comment by timbru31** [comment]
Regarding the log message, I need to debug MC server a bit more, since it seems like a Vanilla log message.

**Comment by AntZaro** [comment]
localization.yml: 
http://pastebin.com/X1sTTXaj

**Comment by timbru31** [comment]
Your localization.yml is invalid - have you modified it? Does the issue persist, if you delete it and restart your server?

**Comment by AntZaro** [comment]
I had the plugin regenerate a new one, and I didn't touch it this time. No more error. I'm not sure what went wrong; I only changed a few words here and there for my own grammar preferences. Oh well. I'll just leave the default to avoid that happening again. Thanks for your help.
