### ISSUE TITLE
Identify cause of log message 'Skipping BlockEntity with id'

### ISSUE THREAD

**Issue by timbru31** [timbru31/SilkSpawners#29]
Originally reported in #28 by @AntZaro 

> When I log on and place spawners, these appear:
> 
> [08:39:48] [Server thread/WARN]: Skipping BlockEntity with id 
> [08:40:03] [Server thread/WARN]: Skipping BlockEntity with id 
> [08:40:21] [Server thread/WARN]: Skipping BlockEntity with id 
> [08:42:32] [Server thread/WARN]: Skipping BlockEntity with id

**Comment by timbru31** [comment]
Crosslink to http://dev.bukkit.org/bukkit-plugins/silkspawners/tickets/111

**Comment by Victhetiger** [comment]
Could it be related in any way with CoreProtect? If it doesn't know the ID and it decides to skip it. Just an idea.

**Comment by Victhetiger** [comment]
I also have to say it doesn't give you the spawner back when you mine it for the sake of this issue, which is pretty bad.

**Comment by timbru31** [comment]
Crosslinking to https://github.com/drtshock/Essentials/issues/469

**Comment by timbru31** [comment]
The log message is located in TileEntity.java from Minecraft itself and is logged when a tile entity could not be found. The _id_ is extracted from get NBTTagCompound which is passed to the method and then looked up (via 1.11 _MinecraftKey_)

**Comment by timbru31** [comment]
EssentialsX seems to mess around with spawners, too. After removing the plugin the message is no longer displayed.
