### ISSUE TITLE
Cant craft Spawner using Spawneggs obtained by crafting.

### ISSUE THREAD

**Issue by MinerlAi** [timbru31/SilkSpawners#294]
## What steps will reproduce the problem?
Enable crafting in config.yml.
Craft a spawnegg using e.G. SpawnEggRecipes (https://dev.bukkit.org/projects/ser), CraftableSpawnEggs (https://dev.bukkit.org/projects/craftable-spawn-eggs).
Try to craft a Spawner.

## Expected output
You can only craft a spawner if you obtain the egg with /give.

## What do you see instead?

##Version
This server is running CraftBukkit version git-Bukkit-3eb7236 (MC: 1.16.4)

## SilkSpawners version

SilkSpawners v6.5.0 --1.8 up to 1.16.4--

## Checklist

- [x] I am aware that issues caused by /reload are ignored
- [x] If there is a (potential) plugin conflict, I've identified the conflicting plugin
- [x] I have added a valid /version output
- [x] I have added a valid SilkSpawners version
- [x] I have attached necessary information like a screenshot, my list of plugins, config or permissions file(s)

**Comment by timbru31** [comment]
Thanks, I’ll take a look at those plugins to give a detailed reason why those do not work.
Does any spawn egg work or none at all?

**Comment by timbru31** [comment]
SpawnEggRecipes latest release is from 2014, this one looks abandoned. I've quickly tested CraftableSpawnEggs v1.2.1, this plugin worked fine for me.

However, I'd advise you to look into datapacks - Minecraft's built in, reliable way to add new recipes: https://minecraft.gamepedia.com/Tutorials/Creating_a_data_pack - all you need is the correct item name (called Namespaced ID, see https://minecraft.gamepedia.com/Java_Edition_data_value#Items), so for a bat egg that would be `minecraft:bat_spawn_egg`
