### ISSUE TITLE
Huge FPS Issue

### ISSUE THREAD

**Issue by bipedd** [timbru31/SilkSpawners#328]
## What steps will reproduce the problem?
Place a few spider or enderman spawners
## Expected output
FPS to not drop over 100 frames from just 10 spider/enderman spawners, I did the same tests with zombie and skeleton spawners and only lost 4-10 fps so this is an issue with these spawners.
## What do you see instead?
Major fps drops from just 10 spawners. Tested over 10+ times.
## Log file of the issue/error
N/A
## /version output?
This server is running Tuinity version git-Tuinity-"2f298d3" (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)

## SilkSpawners version
 7.1.0

## Please provide any additional information below.
This issue only happens with Spider, and endermen spawners
## Checklist

- [x] I am aware that issues caused by /reload are ignored
- [x] If there is a (potential) plugin conflict, I've identified the conflicting plugin
- [x] I have added a valid /version output
- [x] I have added a valid SilkSpawners version
- [x] I have attached necessary information like a screenshot, my list of plugins, config or permissions file(s)

**Comment by timbru31** [comment]
Highly doubt this is SilkSpawners issue - SilkSpawners does not handle spawning, it just sets the correct data tag on the spawner and is done after that.
