### ISSUE TITLE
Some spawner transform in to Pig Spawner 3.7.3 in Spigot 1.10.2

### ISSUE THREAD

**Issue by netherstar** [timbru31/SilkSpawners#34]
When i use 3.7.2 in Spigot 1.9.2, everythings work fine. to day, i just update server to 1.10.2, so silkspawner update to 3.7.3.
After update, some (not all) spawner in server transform in to pig spawner.

**Comment by timbru31** [comment]
Please post you **/version** output

**Comment by philip-ulrich** [comment]
Also getting this issue. My /version is:
This server is running CraftBukkit version git-Spigot-5391d73-0ebb9c7 (MC: 1.10.2) (Implementing API version 1.10.2-R0.1-SNAPSHOT)

**Comment by timbru31** [comment]
@philip-ulrich
Can you give me a bit more details? This makes it easier for me to debug :)
Was the world upgraded to 1.10.2? If yes from what version?
How did you obtain the spawners? (/give, mining, prior to upgrade in inventory)
Did this issue occur with 1.10, too?
All spawners are affected?

Can you eg with PowerNBT tell me what NBT tags are set to the item?

Thanks!

**Comment by philip-ulrich** [comment]
I've already downgraded back to 1.10 so I can't do the last one for you right now, but here is the answers to your other questions:
Was the world upgraded to 1.10.2? If yes from what version?
- _I went from 1.10 to 1.10.2_
How did you obtain the spawners? (/give, mining, prior to upgrade in inventory)
- _With /ss give_
Did this issue occur with 1.10, too?
- _Nope. 1.10 is rainbows and butterflys._
All spawners are affected?
- _Just new spawners or ones changed with /ss change. All mobs are affected. Most you can place and they look okay.. just don't spawn.. you mine it up and it says you destroyed a pig. If you leave and come back, it shows as a pig. Really weird stuff._

**Comment by tuanjr** [comment]
me:
Was the world upgraded to 1.10.2? If yes from what version?
- from 1.9.2
How did you obtain the spawners? (/give, mining, prior to upgrade in inventory)
- from essentialsX give commands and Sign shop
All spawners are affected?
- Not all, somes
