### ISSUE TITLE
when i mine a spawner it doesnt drop, i can also not place it (without OP) (permission issue)

### ISSUE THREAD

**Issue by itsnonotime** [timbru31/SilkSpawners#361]
## What steps will reproduce the problem?
i mine a spawner

## Expected output
chat output + no drops
## /version output?
This server is running CraftBukkit version 3478-Spigot-42b6152-a459f4d (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT)

## SilkSpawners version
silkspawner v7.3.0

## Please provide any additional information below.
once i mine a spawner it doesnt drop the item itself, however there is a message is chat saying the spawner is broken. when trying to place the spawner it says exactly: you do not have permission to place a(n) {mob} spawner! once i try placing a spawner while being OP however i am actually able to place and break the spawners

being op fixes this whole issue, but on a server its not really possible to do that without consequences 

chat message:
![Schermafbeelding 2022-04-16 om 17 09 47](https://user-images.githubusercontent.com/103839887/163680294-4a7f4ff7-8924-4c19-b436-5e7290e8c1a3.png)

plugins: 

![Schermafbeelding 2022-04-16 om 17 12 06](https://user-images.githubusercontent.com/103839887/163680341-6d78363a-29fc-48e4-9374-9587014e79d9.png)
![Schermafbeelding 2022-04-16 om 17 11 57](https://user-images.githubusercontent.com/103839887/163680342-6929f0eb-65b8-41be-b6e6-718679906d20.png)

## Checklist

- [ ] I am aware that issues caused by /reload are ignored
- [ ] If there is a (potential) plugin conflict, I've identified the conflicting plugin
- [x] I have added a valid /version output
- [x] I have added a valid SilkSpawners version
- [x] I have attached necessary information like a screenshot, my list of plugins, config or permissions file(s)

im sorry if its not complete or if i missed something. im quite new to this and couldn't find my answers online

**Comment by timbru31** [comment]
You need to configure the permissions. This is not a bug.

**Comment by Revan7even** [comment]
> You need to configure the permissions. This is not a bug.

I know this is old, but how do we configure permissions if we aren't using World Guard?
I can do everything as an OP and server creator, but no other OPs can.
