### ISSUE TITLE
Minecraft 1.19 update

### ISSUE THREAD

**Issue by PetyXbron** [timbru31/SilkSpawners#363]
# Feature Request

## Motivation Behind Feature

SilkSpawners plugin is not compatible with 1.19. and it disables on the server start. Using version 7.3.0

## /version output?

```Current: git-Purpur-1646 (MC: 1.19)*``` (Paper fork)

## SilkSpawners version

Version: 7.3.0

**Comment by PetyXbron** [comment]
> Your issue does not contain a valid output of the /version command and will now be closed and ignored.
> Please create a new issue, follow the template and include a valid /version output.

@sad-creeper this is my `/version` output:
````
Current: git-Purpur-1646 (MC: 1.19)\*
Previous: git-Paper-"9b6fb2f" (MC: 1.19)
\* You are running the latest version
````
I don't think it's necessary to create a new issue.

**Comment by timbru31** [comment]
Please be patient, it's being worked on.

**Comment by PetyXbron** [comment]
Any updates?

**Comment by mambari** [comment]
@timbru31 hi, do you have some news.
I see that the master is taking the 1.19 but still nothing in https://dev.bukkit.org/projects/silkspawners/files
Btw I will install it on a raspberry pi, is it ok for the java version?
Best regards,
