### ISSUE TITLE
SilkSpawners does not work on 1.19.3

### ISSUE THREAD

**Issue by Bobcat00** [timbru31/SilkSpawners#365]
SilkSpawners does not work on 1.19.3

## Log file of the issue/error

> This version of the plugin is NOT compatible with your Minecraft version!
Compatible versions are: [v1_8_R1, v1_8_R3, v1_9_R2, v1_10_R1, v1_11_R1, v1_12_R1, v1_13_R2, v1_14_R1, v1_15_R1, v1_16_R1, v1_16_R2, v1_16_R3, v1_17_R1, v1_18_R1, v1_18_R2, v1_19_R1]
Your version is: v1_19_R2
java.lang.ClassNotFoundException: de.dustplanet.silkspawners.compat.v1_19_R2.NMSHandler

https://pastebin.com/ekNZ6mYt

## /version output?

This server is running Paper version git-Paper-319 (MC: 1.19.3) (Implementing API version 1.19.3-R0.1-SNAPSHOT) (Git: 1143b63)

## SilkSpawners version

SilkSpawners version 7.3.1-SNAPSHOT-b280

## Checklist

- [x] I am aware that issues caused by /reload are ignored
- [x] If there is a (potential) plugin conflict, I've identified the conflicting plugin
- [x] I have added a valid /version output
- [x] I have added a valid SilkSpawners version
- [x] I have attached necessary information like a screenshot, my list of plugins, config or permissions file(s)

**Comment by Bobcat00** [comment]
No problem. Just wanted to make sure you knew about it.

**Comment by Disorbs** [comment]
bump still having the same issues,.
