### ISSUE TITLE
Allow placing of eggs on top of spawners

### ISSUE THREAD

**Issue by timbru31** [timbru31/SilkSpawners#45]
As in https://www.youtube.com/watch?v=cz0VpLk4mi4
Minecraft allows right click to change since http://minecraft.gamepedia.com/14w28b, this is blocked by SilkSpawners currently and disableChangeTypeWithEgg is for using left click.

**Comment by JokHornsby** [comment]
It's been nearly 4 months since this was recognized: where's the fix?

**Comment by sandor111** [comment]
Has this been fixed yet?

**Comment by timbru31** [comment]
An open issue indicates that the issue is not solved, so no.

**Comment by timbru31** [comment]
Possible now with the settings: 
```yaml
disableChangeTypeWithEgg: true
spawnEggOverride: true
```
