### ISSUE TITLE
Deprecated version matching

### ISSUE THREAD

**Issue by bdotsamir** [timbru31/SilkSpawners#463]
Hey Tim,

I was snooping through to see what your method was for reflection on nms 1.20.2 and saw that it isn't yet here, and I saw [this line](https://github.com/timbru31/SilkSpawners/blob/fbc29a851f0e390c32573bd608debb36c69ccc54/modules/SilkSpawners/src/main/java/de/dustplanet/silkspawners/SilkSpawners.java#L78). Paper released [a notice](https://canary.discord.com/channels/289587909051416579/1077385604012179486/1155459001090318346) the other day that using this method is essentially deprecated, and that the new method that's been around since 2020 is `getServer().getMinecraftVersion()` (or, for more backwards compatibility since 2011: `getServer().getBukkitVersion()`).

I opened an issue for this and not a PR because I'm not sure what your priorities are with supporting older versions.

Thanks!

**Comment by timbru31** [comment]
Protocol  version is checked for Paper >=1.20.5: https://github.com/timbru31/SilkSpawners/commit/a0edc4de2a6c5d6c4bf91f8ca399c314d4a5fb41
