### ISSUE TITLE
Empty spawners with place and break permissions

### ISSUE THREAD

**Issue by Elijahzeal** [timbru31/SilkSpawners#510]
## What steps will reproduce the problem?
1) Mine spawner with silktouch and with break permission, place said spawner with place permission.

2) Give spawner from the /silkspawner give command
## Expected output
1) Spawner should place said type.

2) Spawner should place said type.
## What do you see instead?
1) Spawner places as an empty spawner.

2) Spawner places as an empty spawner.
## Log file of the issue/error
no error is given

## /version output?
This server is running Paper version git-Paper-318 (MC: 1.20.2) (Implementing API version 1.20.2-R0.1-SNAPSHOT) (Git: 9271ee7)
You are running the latest version

## SilkSpawners version
SilkSpawner_v2 v2.2.1

## Please provide any additional information below.
RoseStacker doesn't cause any effect to this issue after checking.

## Checklist

Example Video:
https://github.com/timbru31/SilkSpawners/assets/53013565/eac87124-a89e-4178-8947-3d7455307b95
SilkSpawners config: 
![image](https://github.com/timbru31/SilkSpawners/assets/53013565/b61129ee-ca05-4662-b09b-12a67197c1b0)
Plugins: 
![image](https://github.com/timbru31/SilkSpawners/assets/53013565/20f45511-cc10-4c0b-bdfc-e67441abf139)

- [x] I am aware that issues caused by /reload are ignored
- [x] If there is a (potential) plugin conflict, I've identified the conflicting plugin
- [x] I have added a valid /version output
- [x] I have added a valid SilkSpawners version
- [x] I have attached necessary information like a screenshot, my list of plugins, config or permissions file(s)

**Comment by timbru31** [comment]
> SilkSpawner_v2 v2.2.1

You are using another SilkSpawners plugin, not this one. Please report it to https://github.com/CorneliusMa/SilkSpawners_v2
