### ISSUE TITLE
slime spawner

### ISSUE THREAD

**Issue by dwa1275** [timbru31/SilkSpawners#52]
slime spawner does not work, when placed there is no mob, and errors, I'm sure its just a missing space in code, current spawner is slimedisplayholographis

**Comment by timbru31** [comment]
Sounds like a plugin conflict. I'll take a look at Holographic Displays and ping the author, if I'll find something.

**Comment by timbru31** [comment]
Issue is caused by https://github.com/filoghost/HolographicDisplays/issues/44, closing this since I am unable to change this.
