### ISSUE TITLE
Blaze spawner

### ISSUE THREAD

**Issue by Mrufkojad** [timbru31/SilkSpawners#53]
Hey.
I'm using other spawner plugin, but I have one problem and I wonder if yours will solve this. Players can't mine blaze spawners in nether (that's good), but they can change it's type with an egg and then mine. Does you plugin block this?

**Comment by timbru31** [comment]
You can achieve this by setting world-specific permissions (bPermissions, PEX, ... support those). You can deny any silkspawners permission in the nether (e.g. changetypewithegg), but allow it in overworld.
Does this answer your question?

**Comment by Mrufkojad** [comment]
Yes, almost. How can I negate the permission in other world?

25 gru 2016 22:17 "Tim Brust" <notifications@github.com> napisał(a):

**Comment by timbru31** [comment]
That depends on your permissions plugin, you have to look that up on their documentation page(s).

**Comment by Mrufkojad** [comment]
Okey, I'll do that. Thank you for response.

26 gru 2016 00:17 "Tim Brust" <notifications@github.com> napisał(a):

> That depends on your permissions plugin, you have to look that up on their
> documentation page(s).
>
> Sent from my iPhone
>
