### ISSUE TITLE
Enhancement request - please allow us to have spawners be automatically picked up

### ISSUE THREAD

**Issue by 0x1x2** [timbru31/SilkSpawners#56]
Title says all - maybe an additional permission would be nice.

I already have VKAutoPickup installed and they hate it when they forget that spawners don't automatically pickup (incompatibilities) and lose their spawners, which are highly valuable.

**Comment by timbru31** [comment]
Already possible since https://github.com/timbru31/SilkSpawners/commit/8b398119b75c8dbec389392b6663e245a9d2df43
