### ISSUE TITLE
"disableChangeTypeWithEgg" Not Working

### ISSUE THREAD

**Issue by Elioby** [timbru31/SilkSpawners#57]
The "disableChangeTypeWithEgg" option in the config doesn't seem to work, I think it has to do with this line here:

https://github.com/timbru31/SilkSpawners/blob/master/src/main/java/de/dustplanet/silkspawners/listeners/SilkSpawnersPlayerListener.java#L88

I'm pretty sure the boolean operator should be an or ( || ) rather than an and ( && ). That way you're saying, don't do anything if it's not a right click OR if they have disabled change type with egg.

**Comment by sandor111** [comment]
Has this been fixed yet?

**Comment by ShayBox** [comment]
Can't place mobs on spawners with eggs

**Comment by timbru31** [comment]
See https://github.com/timbru31/SilkSpawners/issues/45#issuecomment-633243064
