### ISSUE TITLE
Changing eggs via commands is possible with changetypewithegg

### ISSUE THREAD

**Issue by jordanwilliams1** [timbru31/SilkSpawners#59]
Hello,

It seems anyone can change spawn eggs if they have this permmison: silkspawners.changetypewithegg.*

This permission is only meant to allow users to change spawners with the egg. Not allow them to change the spawner egg to what ever they like.  If they hold a egg in there hand and do /ss change villager. it will change the egg to a villager egg. 

Tried on the latest dev build. Even tried on the official release on bukkit.

**Comment by timbru31** [comment]
Second report for this issue now - even if this was always the way it is. Considering this a bug

**Comment by jordanwilliams1** [comment]
@timbru31 Do you have a eta on when it will be fixed? I've had to disable the plugin till its fixed. People started to make End dragon spawners :/

**Comment by timbru31** [comment]
@jordanwilliams1 dev-build https://ci.dustplanet.de/job/SilkSpawners/390/ takes care of this issue. Could you confirm this?
