### ISSUE TITLE
Permissions to change spawners with eggs don't work properly

### ISSUE THREAD

**Issue by timbru31** [timbru31/SilkSpawners#68]
I use SilkSpawners v3.7.2 with this permissions:
    - silkspawners.changetypewithegg.zombie
    - silkspawners.changetypewithegg.skeleton
    - silkspawners.changetypewithegg.spider
    - silkspawners.changetypewithegg.cavespider
    - silkspawners.place.*
    - silkspawners.silkdrop.*
Players can use any eggs in the spawner.

---
_Migrated from https://dev.bukkit.org/projects/silkspawners/issues/108_

**Comment by RaidersUnited** [comment]
I'm getting the same issue

**Comment by timbru31** [comment]
@RaidersUnited Please post your /version output and your permission file(s), thanks!

**Comment by RaidersUnited** [comment]
Version 3.7.4

Perms:
    - silkspawners.changetypewithegg.*
    - silkspawners.place.*
    - silkspawners.silkdrop.*

**Comment by timbru31** [comment]
As already said:
I need your /version info, not just SikSpawners version and the **full** permission files.

**Comment by RaidersUnited** [comment]
https://pastebin.com/YX16itp7

version: git-Spigot-3fb9445-2b6c9f4 (mcL 1.11.2) (implementing API version 1.11.2-R0.1-SNAPSHOT)

**Comment by timbru31** [comment]
v6.0.1 has been released. If this issue persists, please create a new one. Thanks!
