### ISSUE TITLE
Slime spawners not working

### ISSUE THREAD

**Issue by Indivicous** [timbru31/SilkSpawners#69]
Hello, when placing slime spawners in the correct environment (took many steps in order to match the slime spawner environment), the mobs still won't spawn. This is the only spawner type I have this error with atm. Any help is appreciated, thanks again,

-Indivicous

## /version output?
Spigot 1.8.8-R0.1-Snapshot

## SilkSpawners version
SilkSpawners v3.7.4  
SilkSpawnersShopAddon v1.4.1

## Checklist
- [x] I am aware that issues caused by /reload are ignored
- [ ] If there is a (potential) plugin conflict, I've identified the conflicting plugin
- [ ] I have added a valid /version output
- [x] I have added a valid SilkSpawners version
- [ ] I have attached necessary information like a screenshot, my list of plugins, config or permissions file(s)

**Comment by timbru31** [comment]
Please fill in the issue template correctly and make sure all spawning criteria for slimes are met. SilkSpawners does not alter spawning behavior. If the issue persists, please create a new one with a minimal reproducible example. Thanks!
