### ISSUE TITLE
Plugin resets itself when I restart my server.

### ISSUE THREAD

**Issue by Wardalicious** [timbru31/SilkSpawners#70]
## What steps will reproduce the problem?

I change/edit/remove messages and notifications in the config, so they do not show up in-game, or so that they say exactly what I want them to say. Namely: placing/removing spawners. These notifications become very annoying and spammy. When I have edited everything and save it, the in-game effects are flawless. The issue arises, when I restart my server. When doing that, the entire plugin resets back to default, and all the changes I made(anywhere) get removed and reset.

## Expected output

I want the changes to remain xD I want to be able to have the messages say exactly what I want them to say, when i edit them in the config. I do not want a server restart to wipe all my changes and reset the plugin back to default settings.

## Log file of the issue/error

 I was not able to locate any error or log file showing this happening. It's just like... gone.

## /version output?

"This server is running CraftBukkit version git-Spigot-c6871e2-0cd0397 (MC: 1.9.4) (Implementing API version 1.9.4-R0.1-SNAPSHOT)"
"You are 321 version(s) behind"

## SilkSpawners version

v3.7.4

## Please provide any additional information below.

List of plugins:
- http://prntscr.com/eg2pwv
- http://prntscr.com/eg2qk9

Silk Spawners Config:
- http://prntscr.com/eg2rz4
- http://prntscr.com/eg2s5b
- http://prntscr.com/eg2sa7
- http://prntscr.com/eg2seg

Permissions:
- http://prntscr.com/eg2sz7
- http://prntscr.com/eg2t30
- http://prntscr.com/eg2t78
- http://prntscr.com/eg2tbf
- http://prntscr.com/eg2thc
- http://prntscr.com/eg2tnt
- http://prntscr.com/eg2tt7

## Checklist

- [x] I am aware that issues caused by /reload are ignored
- [x] If there is a (potential) plugin conflict, I've identified the conflicting plugin
- [x] I have added a valid /version output
- [x] I have added a valid SilkSpawners version
- [x] I have attached necessary information like a screenshot, my list of plugins, config or permissions file(s)

**Comment by timbru31** [comment]
@Wardalicious Thanks for using the issues template!
Could you possibly upload your config.yml to e.g. http://pastebin, when you made edits?

**Comment by timbru31** [comment]
ping @Wardalicious

**Comment by timbru31** [comment]
Closing due to lack of response.  
If the issue persists, please let me know @Wardalicious
