### ISSUE TITLE
Spawners not working

### ISSUE THREAD

**Issue by ItsSh4dow** [timbru31/SilkSpawners#71]
## What steps will reproduce the problem?
The mobs sometimes don't spawn my spawners. I need to replace the spawner so mobs can spawn. Sometimes I need to change the difficulty to 1 even when it is set to 1 to work. I don't know whats going on. The 'when' is undefined

## Expected output
Mobs spawn always

## Log file of the issue/error
No log

## /version output?
CraftBukkit version git-spigot-db6de12-d3e0b6f (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT) You are 610 versions behind

## SilkSpawners version
3.7.4

## Please provide any additional information below.
https://hastebin.com/okewikiwoh.bash

## Checklist

- [x] I am aware that issues caused by /reload are ignored
- [x] If there is a (potential) plugin conflict, I've identified the conflicting plugin
- [x] I have added a valid /version output
- [x] I have added a valid SilkSpawners version
- [x] I have attached necessary information like a screenshot, my list of plugins, config or permissions file(s)

**Comment by timbru31** [comment]
Spawning algorithm is not changed by SilkSpawners.
