### ISSUE TITLE
SilkSpawner can't be placed or mined

### ISSUE THREAD

**Issue by zAnonimo** [timbru31/SilkSpawners#72]
## What steps will reproduce the problem?
When trying mining a spawner (with silktouch ofc) it's says "*mob* spawner broken!" but doesn't do anything. Same when placing a spawner, says that I don't have permissions to place *mob* spawner.

My default group user have this permissions:
```yaml
    - silkspawners.info
    - silkspawners.viewtype
    - silkspawners.place.creeper
    - silkspawners.place.skeleton
    - silkspawners.place.spider
    - silkspawners.place.zombie
    - silkspawners.place.cavespider
    - silkspawners.place.blaze
    - silkspawners.place.pig
    - silkspawners.place.sheep
    - silkspawners.place.cow
    - silkspawners.place.chicken
    - silkspawners.silkdrop.creeper
    - silkspawners.silkdrop.skeleton
    - silkspawners.silkdrop.spider
    - silkspawners.silkdrop.zombie
    - silkspawners.silkdrop.cavespider
    - silkspawners.silkdrop.blaze
    - silkspawners.silkdrop.pig
    - silkspawners.silkdrop.sheep
    - silkspawners.silkdrop.cow
    - silkspawners.silkdrop.chicken
```

## Expected output
Let me do these things when having the correct permissions nodes on my PEX.

## Log file of the issue/error
I don't get any error on console.

## /version output?
CraftBukkit version git-Spigot-96235ab-2aa5ac6 (MC: 1.11.2)

## SilkSpawners version
SilkSpawners v3.8-SNAPSHOT-b396

## Please provide any additional information below.
If I have '*' permissions on my PEX, or OP I can place and pick them, but users can't even if I place them the correct permissions nodes.

Plugin list:
`Plugins (32): dynmap, WorldEdit, Essentials, ClearLag, AutoMessage, AdvancedMultiLanguage, WorldGuard, ProtocolLib, SkinsRestorer, AutoRestart, EssentialsProtect, EssentialsGeoIP, EssentialsChat, PermissionsEx, mcMMO, Vault, EssentialsSpawn, MarriageMaster, CompatNoCheatPlus, PlotSquared, SilkSpawners, Multiverse-Core, NoCheatPlus, SignColors, MythicMobs, ShopChest, GriefPrevention, AreaShop, AuthMe, MobArena, Jobs, HolographicDisplays`

## Checklist
- [ ] I am aware that issues caused by /reload are ignored
- [ ] If there is a (potential) plugin conflict, I've identified the conflicting plugin
- [x] I have added a valid /version output
- [x] I have added a valid SilkSpawners version
- [x] I have attached necessary information like a screenshot, my list of plugins, config or permissions file(s)

**Comment by timbru31** [comment]
Does v3.7.4 work? Helps me a lot to to know a good/working version.  
And thanks for using the template :)

**Comment by zAnonimo** [comment]
I tried with v3.7.4 and had the same problem. I updated to DEV Build just to make sure isnt that version.

**Comment by timbru31** [comment]
Memo to self: check output from mobName variable - https://github.com/timbru31/SilkSpawners/blob/master/modules/SilkSpawners/src/main/java/de/dustplanet/silkspawners/listeners/SilkSpawnersBlockListener.java#L89

**Comment by timbru31** [comment]
I could not re-produce this issue, if you can provide a [Minimal Working Example](https://en.wikipedia.org/wiki/Minimal_Working_Example), I'm happy to re-open this issue.

My guess: a plugin conflict with either
- a shop plugin
- any mob plugin
- world protection plugin
