### ISSUE TITLE
spawn egg issue

### ISSUE THREAD

**Issue by DarkMonolith** [timbru31/SilkSpawners#73]
## What steps will reproduce the problem?

Attempting to give the player a spawn egg item through use of command (exception /ss)

## Expected output

The player receives a spawn egg

## Log file of the issue/error

Error: 'null'. Nothing gets printed to log when error occurs

## /version output? 

1.11.2-R0.1-SNAPSHOT (9 versions behind)

## SilkSpawners version

3.7.4

## Checklist

- [x] I am aware that issues caused by /reload are ignored
- [x] If there is a (potential) plugin conflict, I've identified the conflicting plugin
- [x] I have added a valid /version output
- [x] I have added a valid SilkSpawners version
- [think so ] I have attached necessary information like a screenshot, my list of plugins, config or permissions file(s)

**Comment by timbru31** [comment]
Can you please try a dev build?
https://ci.dustplanet.de/job/SilkSpawners/396/

**Comment by DarkMonolith** [comment]
it didnt fix anything

**Comment by timbru31** [comment]
The error is not fully posted by you, I'll need the whole stacktrace, that's in the log

**Comment by DarkMonolith** [comment]
stacktrace?

**Comment by DarkMonolith** [comment]
this is all that gets printed in the logs. The last line or two is me trying to give myself a spawn egg

[14:44:11] [pool-3-thread-27/INFO]: [Vault] Checking for Updates ... 
[14:44:11] [pool-3-thread-24/INFO]: [PlayerVaults] We didn't find an update!
[14:44:11] [Server thread/INFO]: [ASkyBlock] Loading island grid...
[14:44:11] [Server thread/INFO]: [ASkyBlock] Loading islands.yml
[14:44:11] [Server thread/INFO]: [ASkyBlock] Loading warps...
[14:44:11] [pool-3-thread-27/INFO]: [Vault] No new version available
[14:44:11] [Server thread/INFO]: [ASkyBlock] All files loaded. Ready to play...
[14:44:12] [pool-3-thread-30/INFO]: [BossShopPro] Loaded 10 Shops!
[14:44:12] [pool-3-thread-30/INFO]: [BossShopPro] Vault found.
[14:44:12] [Server thread/INFO]: [ASkyBlock] No update available.
[15:22:11] [Server thread/INFO]: CONSOLE issued server command: /give DarkUnicornMeow 383 1
[15:22:11] [Server thread/INFO]: [0;31;1mError:[0;31;22m null[m

**Comment by timbru31** [comment]
You use give. Not /ss give - /give is *not* part of SilkSpawners

**Comment by DarkMonolith** [comment]
but I dont want a ss spawn egg. Even if I add a spawn egg to a /kit it doesnt give it to my player

**Comment by DarkMonolith** [comment]
how am I supposed to give myself eggs through means other than silkspawners?

**Comment by timbru31** [comment]
Creative mode, SilkSpawners built in commands, other plugins that use SilkSpawners API to create new egg items

**Comment by DarkMonolith** [comment]
so I cant give eggs through /i /give or /kit?

**Comment by timbru31** [comment]
No, Essentials is broken. I'm not sure if [EssentialsX](https://github.com/drtshock/Essentials) is working fine, since I'm not playing Minecraft anymore.

**Comment by DarkMonolith** [comment]
I guess theres no way, then. EssentialsX is what I use. Do you know if theres any way to make it so spawn eggs are different from ss spawn eggs?

**Comment by timbru31** [comment]
SilkSpanwers just gives you normal spawn eggs with correct NBT data which contains the information which mob should be spawned. This influences the "skin" of the egg, too.

EssentialsX should work with eggs, maybe your build is outdated: https://github.com/drtshock/Essentials/issues/976
