### ISSUE TITLE
pumpling spawner issues

### ISSUE THREAD

**Issue by CakeLady** [timbru31/SilkSpawners#74]
## What steps will reproduce the problem?
plumpling spawners (is that what zombie spawners are called now?) cannot be picked up with silk touch
## Expected output
expect to be able to silk touch pumpling spawners
## Log file of the issue/error
https://pastebin.com/gcMDyfhM

## /version output?
30.03 21:08:56 [Server] INFO This server is running CraftBukkit version git-Spigot-625bc00-d09304e (MC: 1.11.2) (Implementing API version 1.11.2-R0.1-SNAPSHOT)

## SilkSpawners version
3.7.4

## Please provide any additional information below.
When i place it, it says in chat "pumpling spawner placed, and it has no entity inside the spawner but it spawns zombies.
When I silk touch the spawner it says in chat "0 Spawner broken"
## Checklist

- [x] I am aware that issues caused by /reload are ignored
- [x] If there is a (potential) plugin conflict, I've identified the conflicting plugin
- [x] I have added a valid /version output
- [x] I have added a valid SilkSpawners version
- [x] I have attached necessary information like a screenshot, my list of plugins, config or permissions file(s)

**Comment by timbru31** [comment]
Could you please test a recent dev build? https://ci.dustplanet.de/job/SilkSpawners/396/

**Comment by CakeLady** [comment]
I just gave it a go and no, still have the same problems

**Comment by CakeLady** [comment]
Sorry for the delay, i will try and test faster in the future =o)

**Comment by timbru31** [comment]
Do you have an updated log file for me with the dev build?

**Comment by CakeLady** [comment]
All it says is:
04.04 04:11:18 [Server] WARN [SilkSpawners] Skipping invalid spawner to set NBT data on.
04.04 04:11:18 [Server] WARN [SilkSpawners] Skipping dropping of spawner, since item is null

**Comment by CakeLady** [comment]
All it says is:
04.04 04:11:18 [Server] WARN [SilkSpawners] Skipping invalid spawner to set NBT data on.
04.04 04:11:18 [Server] WARN [SilkSpawners] Skipping dropping of spawner, since item is null

**Comment by CakeLady** [comment]
It also seems to be having a hard time passing the info to coreprotect, not sure if that is your end or not:
https://pastebin.com/YDKBzvyt

**Comment by timbru31** [comment]
SilkSpawners dev build prevents the error - CoreProtect not. However I believe that another plugins causes a conflict. Could you narrow it down to a conflicting one? (Disable one plugin a time)

**Comment by CakeLady** [comment]
for which part? the spawner not being able to be silked or the core protect conflict?

**Comment by timbru31** [comment]
The spawner not being able to be silked.

**Comment by CakeLady** [comment]
it was all working until recently, i think after the last spigot update, and i haven't added any new plugins.

**Comment by timbru31** [comment]
Thanks, that helps. Any chance you know the /version from the last working version?
(or at least if you just updated an existing 1.11.2 build or upgraded from e.g. MC 1.8)

**Comment by timbru31** [comment]
Note to self, this could be related to the issue, since https://github.com/timbru31/SilkSpawners/blob/master/modules/v1_11_R1/src/main/java/de/dustplanet/silkspawners/compat/v1_11_R1/NMSHandler.java#L248 calls `asCraftMirror`
https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/commits/7fce67144dd1b610d4c250939f194b04b0f64a9e
https://hub.spigotmc.org/jira/browse/SPIGOT-3108

**Comment by CakeLady** [comment]
i might be able to figure it out... let me try

**Comment by CakeLady** [comment]
I was updating from an existing 1.11.2 build for sure, not sure of the exact build previously

**Comment by CakeLady** [comment]
we are also having issues with the spider spawners, which recently changed into rideablespiders? this spawner is also having the same issue.

**Comment by timbru31** [comment]
Could you possibly post a list of your plugins, too?

**Comment by CakeLady** [comment]
https://gyazo.com/4fed33359a3b770099411ce3f03837f5
plus shopchest

**Comment by CakeLady** [comment]
all the other spawners seem to be working fine

**Comment by timbru31** [comment]
Uff that list is too big for me to test.
Running SilkSpawners with the latest Spigot and CraftBukkit builds without issues.
Can you please narrow the conflicting plugin down?

**Comment by timbru31** [comment]
@CakeLady I'd vote that SimplePets could be a good cause of the problem - it's known for being conflicting in the past.

**Comment by CakeLady** [comment]
ill try taking it out and see if it works, but they were working together fine before. ill let you know

**Comment by CakeLady** [comment]
ok we took out the pets plugin and we still cannot silk the pumpling spawners

**Comment by CakeLady** [comment]
we placed a new spawner and got this error:
06.04 15:50:25 [Server] WARN Skipping BlockEntity with id 
https://pastebin.com/TZ0J2d2h

Then received the same errors above when trying to break them

**Comment by CakeLady** [comment]
I tried removing the simpleAPI also and same result with both of those plugins removed

**Comment by timbru31** [comment]
That issue should be reported to CoreProtect, too 👍 
However, you need to debug more which plugin conflicts 😕  - I'd recommend to use e.g. [this](https://www.spigotmc.org/resources/api-pluginmanager-1-8-1-9-1-10-1-11.18047/) plugin to disable each plugin a time and retry until you find the culprit.

**Comment by CakeLady** [comment]
I placed a pig spawner and changed it to pumpling and tried to silk it:
06.04 16:09:06 [Server] INFO Cake_Lady issued server command: /ss set pumpling
06.04 16:09:07 [Server] INFO CONSOLE issued server command: /list 
06.04 16:09:07 [Server] INFO Admins: Cake
06.04 16:09:07 [Server] INFO SrMod: Aka
06.04 16:09:09 [Server] INFO [Statz debug] Save Statz database.
06.04 16:09:12 [Server] WARN [SilkSpawners] Skipping invalid spawner to set NBT data on.
06.04 16:09:12 [Server] WARN [SilkSpawners] Skipping dropping of spawner, since item is null

**Comment by timbru31** [comment]
Please disable UltraCosmetics and see if things are working again. Note: you might need to use zombie over pumpling again when this plugin is disabled

**Comment by CakeLady** [comment]
Ok let me give that a go

**Comment by CakeLady** [comment]
omg that is it! I will report it to the plugin owner, thanks!

**Comment by timbru31** [comment]
I will, since I know what technical fault it is 👍

**Comment by CakeLady** [comment]
excellent, thank you so much for your help with this!

**Comment by timbru31** [comment]
You're welcome.
