### ISSUE TITLE
Permissions Issue

### ISSUE THREAD

**Issue by ColeDidy** [timbru31/SilkSpawners#75]
## What steps will reproduce the problem?
N/A
## Expected output
Permissions are not working. Using PEx
## /version output?
Paper version git-TacoSpigot-"2b961b0f" (MC: 1.11.2) (Implementing API version 1.11.2-R0.1-SNAPSHOT)

## SilkSpawners version
3.7.4

## Please provide any additional information below.
The plugin works for OPs and users with *. We tried using the permissions listed on the Bukkit page, they did not work. Please contact me back ASAP. coledidy@thehypernova.com
Thank you.

## Checklist

- [x] I am aware that issues caused by /reload are ignored
- [N/A] If there is a (potential) plugin conflict, I've identified the conflicting plugin
- [X] I have added a valid /version output
- [X] I have added a valid SilkSpawners version
- [N/A] I have attached necessary information like a screenshot, my list of plugins, config or permissions file(s)

**Comment by timbru31** [comment]
Without further information like the PEX or SilkSpawners config I'm unable to assist.

**Comment by timbru31** [comment]
Closing due to lack of response.  
If the issue persists, please let me know @ColeDidy
