### ISSUE TITLE
When placing any spawner The spawner switch to a pig

### ISSUE THREAD

**Issue by DanielTravi** [timbru31/SilkSpawners#81]
## What steps will reproduce the problem?

- Put spawners

 ## Expected output

That when I will put it the mob corresponding to the spawner and not the pig that is the mob that is by default

 ## What do you see instead?

That all the spawners I put in become pork spawners. And I get this error:

09.06 19:21:08 [Server] WARN Skipping BlockEntity with id 
09.06 19:21:08 [Server] WARN Skipping BlockEntity with id 
09.06 19:21:08 [Server] WARN Skipping BlockEntity with id 

## Log file of the issue/error

09.06 19:21:08 [Server] WARN Skipping BlockEntity with id 
09.06 19:21:08 [Server] WARN Skipping BlockEntity with id 
09.06 19:21:08 [Server] WARN Skipping BlockEntity with id 

## /version output?

Spigot 1.11.2

## SilkSpawners version

3.7.4

## Please provide any additional information below.

Reload:

09.06 19:30:10 [Server] INFO Loading custom recipes
09.06 19:30:10 [Server] INFO Amount of wither: 1
09.06 19:30:10 [Server] INFO Shape of wither:
09.06 19:30:10 [Server] INFO AAA
09.06 19:30:10 [Server] INFO AXA
09.06 19:30:10 [Server] INFO AAA
09.06 19:30:10 [Server] INFO Ingredients of wither:
09.06 19:30:10 [Server] INFO [A,IRON_FENCE]
09.06 19:30:10 [Server] INFO shape of wither contains X
09.06 19:30:10 [Server] INFO Amount of bat: 1
09.06 19:30:10 [Server] INFO Shape of bat:
09.06 19:30:10 [Server] INFO AAA
09.06 19:30:10 [Server] INFO AXA
09.06 19:30:10 [Server] INFO AAA
09.06 19:30:10 [Server] INFO Ingredients of bat:
09.06 19:30:10 [Server] INFO [A,IRON_FENCE]
09.06 19:30:10 [Server] INFO shape of bat contains X
09.06 19:30:10 [Server] INFO Amount of witch: 1
09.06 19:30:10 [Server] INFO Shape of witch:
09.06 19:30:10 [Server] INFO AAA
09.06 19:30:10 [Server] INFO AXA
09.06 19:30:10 [Server] INFO AAA
09.06 19:30:10 [Server] INFO Ingredients of witch:
09.06 19:30:10 [Server] INFO [A,IRON_FENCE]
09.06 19:30:10 [Server] INFO shape of witch contains X
09.06 19:30:10 [Server] INFO Amount of endermite: 1
09.06 19:30:10 [Server] INFO Shape of endermite:
09.06 19:30:10 [Server] INFO AAA
09.06 19:30:10 [Server] INFO AXA
09.06 19:30:23 [Multicraft] Skipped 727 lines due to rate limit (30/s)

**Comment by timbru31** [comment]
The log message (Skipping BlockEntitt with id) is from Minecraft itself and mostly caused by Essentials.  
Your issue is a plugin conflict, please debug it further, by disabling a plugin each time, until the placement of the spawner worked.

**Comment by DanielTravi** [comment]
I have tried doing this several times and it doesn't fix

**Comment by timbru31** [comment]
Have you tried just SilkSpawners?
Besides that you have not included a valid /version output.

**Comment by DanielTravi** [comment]
If I have tried it and I have restarted the essentials and silkspawners plugins

**Comment by DanielTravi** [comment]
How could you solve the problem? It also proves to delete the files of the plugin

**Comment by Arcadexe** [comment]
I'm having the same problem and can't fix it, I have tried multiple tries and didn't seem to work, I would love if this got a early response, I really need to release my server,

Thank you

**Comment by timbru31** [comment]
As already stated, disable one plugin a time, restart (not reload) the server, until you have identified the conflicting plugin(s). Otherwise I'm unable to help.

**Comment by Faicu** [comment]
I have this problem too, mention me when you found the plugin conflict, thanks

**Comment by timbru31** [comment]
@DanielTravi @Arcadexe @Faicu please try one of the latest dev builds: https://ci.dustplanet.de/job/SilkSpawners/435/

**Comment by Fonzee9** [comment]
I am having the same problem.. Build 446

**Comment by timbru31** [comment]
I'm cleaning up old issues. If this issue still persists, please comment here and I'll re-open this issue.
