### ISSUE TITLE
Spawners Randomly Turn into Pig Spawners

### ISSUE THREAD

**Issue by Fluxty** [timbru31/SilkSpawners#83]
## What steps will reproduce the problem?

The issue happens at complete random, there is no known way to envoke it with 100% success.

## Expected output

We expect spawners to continually spawn the type of mob it is set to.

## What do you see instead?

SOMETIMES, a spawner will just lose all its NBT data and become a pig spawner. It's really flared up with the latest version of SilkSpawners, people are losing spawners left and right, we're having to come verify and refund them, and it's causing us to lose any actual time to work on the server. (With 400+ players online we are jumping through hoops trying to refund stuff)

## Log file of the issue/error

Nothing. We see Skipping Block Entity with ID every time a spawner is placed, but that's about it.

## /version output?

This server is running CraftBukkit version git-TacoSpigot-"65fd35f" (MC: 1.8.8) (Implementing API version 1.8.8-R0.2-SNAPSHOT)
You are 2 version(s) behind

## SilkSpawners version

4.0.0

## Please provide any additional information below.

We're using MergedSpawner - https://www.spigotmc.org/resources/mergedspawner-mcmmo-silkspawner-etc-support-included.31982/ - and I've also contacted him about this issue. 

Other notable plugins:
AAC (Contacted about the issue potentially revolving around chunk loads and unloads)
AskyBlock
Essentials
ClearLag
FastAsyncWorldEdit

We cannot pinpoint an exact plugin conflict because the issue occurs at random and I have not yet been able to reproduce it. We can't disable plugins one by one in a production environment where many are playing.

## Checklist

- [x] I am aware that issues caused by /reload are ignored
- [] If there is a (potential) plugin conflict, I've identified the conflicting plugin
- [x] I have added a valid /version output
- [x] I have added a valid SilkSpawners version
- [x] I have attached necessary information like a screenshot, my list of plugins, config or permissions file(s)

**Comment by tactustyler** [comment]
I'm having the exact same issue. Please find a solution soon. This is causing quite a bit of issues with players on my server who've purchased spawners.

**Comment by timbru31** [comment]
Without an reproducible example, this is black box for me. Especially if the issue happens at random.  
You guys can help me if you install e.g. https://www.spigotmc.org/resources/powernbt.9098/ and issue `/nbt block` and screenshot me the results.

**Comment by Fluxty** [comment]
I've found that the main issue here was with AAC's /restorechunk command, removing that, the issue has become very rare.  Likely not a SilkSpawners issue

**Comment by timbru31** [comment]
Thanks for letting me know, I'll debut this.

**Comment by Fonzee9** [comment]
I am having the same problem.. Build 446

**Comment by timbru31** [comment]
I'm cleaning up old issues. If this issue still persists, please comment here and I'll re-open this issue.
