### ISSUE TITLE
Can't get silkspawners to to work but plugin enables with config option

### ISSUE THREAD

**Issue by popanakes** [timbru31/SilkSpawners#84]
## What do you see instead?
Repeats the /ss help command even when typing /ss help

## /version output?
1.11.2 is our server version When I type the command it shows This server is not running any plugin by that name

## SilkSpawners version
Hi I tried downloading the versions from the Spigot Website and the Bukkit website. After that I tried downloading from the jenkins website and those builds were > 420 - 423

## Please provide any additional information below.
I tried of course switching the plugin around to different versions and this would still cause the plugin to remain RED in the plugin list but once I set testMCVersion: false it seemed to load and turn green but would only allow the /ss help command to be shown and when typed nothing else would come up except the use /ss help. I made sure to type the command as OP as well. 

Plugins screenshot >> https://gyazo.com/93f6e4f58e541c5d2608ba5ddf905c9e

Tried to upload the config.yml but not support. I believe however the only line I have edited was the percentages to drop (I left the spawners to drop at 100) but disabled the eggs etc, and the other testMCVersion: false to get the plugin to load.

Thanks for any help! Been using the plugin for a long time and can't wait to get it running again for my players. 

## Checklist

- [x] I am aware that issues caused by /reload are ignored
- [x] (I don't see a potential conflict but I uploaded my list to be sure) If there is a (potential) plugin conflict, I've identified the conflicting plugin
- [x] I have added a valid /version output
- [x] I have added a valid SilkSpawners version
- [x] I have attached necessary information like a screenshot, my list of plugins, config or permissions file(s)

**Comment by popanakes** [comment]
It seems the problem was NMS side and I was able to fix it myself with a little editing.

**Comment by timbru31** [comment]
Could you elaborate what exactly you mean?
