### ISSUE TITLE
How to give spawners in /kits

### ISSUE THREAD

**Issue by Bedtimeguys** [timbru31/SilkSpawners#85]
## Checklist

- [ ] I am aware that issues caused by /reload are ignored
- [ ] If there is a (potential) plugin conflict, I've identified the conflicting plugin
- [ ] I have added a valid /version output
- [ ] I have added a valid SilkSpawners version
- [ ] I have attached necessary information like a screenshot, my list of plugins, config or permissions file(s)

**Comment by popanakes** [comment]
You will need to make a Command type in your Config - 

Example

      '1':
        Type: COMMAND
        Commands:
        - 'give %name% 52:54 1''
        Item Type: DIAMOND_AXE
        Item Data: 0
        Percentage: ???
        Name: Zombie Spawner | 1
        Amount: 1
        Enchantments:
        -

**Comment by Bedtimeguys** [comment]
Where would this be? Inside the silkspawners config or? Because i want it
so when they type say /kit Warrior they will get the kit and a spawner.

**Comment by popanakes** [comment]
essentials config
kits:
  starter:
    delay: 86400
    items:
      - 52:54 1

**Comment by Bedtimeguys** [comment]
Thank you for the fast response will let you know if it works!

**Comment by timbru31** [comment]
As already linked on Spigot, correct way to use it is the lore. https://www.spigotmc.org/threads/essentials-spawners-in-1-8.37148/page-2#post-648144

**Comment by Bedtimeguys** [comment]
Only one issue when i get the kit it says and i quote "Placing default
spawner (either this spawner is invalid or disabled)
