### ISSUE TITLE
Can't stack spawners

### ISSUE THREAD

**Issue by Lokiro67** [timbru31/SilkSpawners#86]
## What steps will reproduce the problem?
Trying to stacks spawner with option in true

# Should spawners be stackable
spawnersUnstackable: true

## Expected output
nothing

## /version output?
version: git-spigot-b78586d-7638276 (1.12)
API version 1.12- R1-snapshot

## SilkSpawners version
V4.0 last release

## Checklist

- [x] I am aware that issues caused by /reload are ignored
- [x] If there is a (potential) plugin conflict, I've identified the conflicting plugin
- [x] I have added a valid /version output
- [x] I have added a valid SilkSpawners version
- [x] I have attached necessary information like a screenshot, my list of plugins, config or permissions file(s)

**Comment by timbru31** [comment]
Please add a valid /version output - the one you provided is invalid. This helps me **a lot** to fix issues faster!

**Comment by timbru31** [comment]
If you want to stack spawners, make sure `spawnerUnstackable` is set to **false**, not true.

**Comment by Lokiro67** [comment]
version: git-spigot-b78586d-7638276 (1.12)
API version 1.12- R1-snapshot

so i have tested with false but dont work too and if is false the description is so wrong
Should spawners be stackable

**Comment by timbru31** [comment]
I've re-tested the issue - spawner stack fine when spawnerUnstackable is set to false, they stack up to 64 which is the Vanilla default. If set to true stacking no longer works.
