### ISSUE TITLE
Api not working with worldguard

### ISSUE THREAD

**Issue by Gcunhaa** [timbru31/SilkSpawners#87]
## What steps will reproduce the problem?
Start the plugin

## Expected output
Hook to WorldGuard without problems

## What do you see instead?
https://hastebin.com/otuyeluqic.css

## Log file of the issue/error

https://hastebin.com/otuyeluqic.css

## /version output?
This server is running CraftBukkit version git-Spigot-21fe707-e1ebe52 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)

## SilkSpawners version
 v4.0.0

## Please provide any additional information below.
It works perfectly without worldguard but when worldguard is enabled, doesnt work.
(Even a simple e.setCanceled(true) on the SpawnerPlaceEvent wont work with worldguard)

## Checklist

- [x] I am aware that issues caused by /reload are ignored
- [x] If there is a (potential) plugin conflict, I've identified the conflicting plugin
- [x] I have added a valid /version output
- [x] I have added a valid SilkSpawners version
- [x] I have attached necessary information like a screenshot, my list of plugins, config or permissions file(s)

**Comment by Gcunhaa** [comment]
Can you help me fix this @timbru31 ?

**Comment by timbru31** [comment]
Could you paste a snippet of your code where you interact with the SilkSpawners API please?

**Comment by timbru31** [comment]
Crossref #62

**Comment by timbru31** [comment]
Ping @Gcunhaa 

> Could you paste a snippet of your code where you interact with the SilkSpawners API please?

**Comment by timbru31** [comment]
See https://github.com/timbru31/SilkSpawners/issues/90#issuecomment-317538774
