### ISSUE TITLE
Break=turns to pigspawner

### ISSUE THREAD

**Issue by AceDracule** [timbru31/SilkSpawners#89]
## What steps will reproduce the problem?
every time a spawner is placed by any player then broken again wether it may have been purchased from shop or found in the wild once broken imidiatly turns into pig spawner everytime
## Expected output
after breaking the spawner it should br droped as the entity data and original specified entity data
## /version output?
from what information i can get without asking the admin team 4.0.0

## SilkSpawners version
4.0.0

## Please provide any additional information below.
okay so this didnt originally start until there was a change in shop adding the SSsignshop into the server i am helping to dev a design, along with this i had noted after looking threw numerous other issues that are relativley the same there was still some very important information i feel was left out,

extending further on this thought i would like to mention that the version of mincraft the server is running currently is at 1.12 release, with a spigot format.  now with that out of the way i have noticed that threw looking over other simlar issues there seems to be a conflict between either: world guard, Essentials basics (the essentials package 6 am typeing this out), and possably an api appendix issue.

i had done some slight testing in the server itself unfortunately being as late as it was i could only do so much but the larget thing i noted was that it was mainly after the additional shop plug in was added to allow players to use there in game currency to purchase spawner from shop is when this really started to become an issue within the server itself.

i think just think that it may have something to do specifically with world guard and entity data as world guard is known to claim entities adding further data onto the entity please look into this before asking for a screen shot 
## Checklist

- [ ] I am aware that issues caused by /reload are ignored
- [ ] If there is a (potential) plugin conflict, I've identified the conflicting plugin
- [ ] I have added a valid /version output
- [ ] I have added a valid SilkSpawners version
- [ ] I have attached necessary information like a screenshot, my list of plugins, config or permissions file(s)

**Comment by timbru31** [comment]
Please provide a valid /version output and try dev build 435 from here: https://ci.dustplanet.de/job/SilkSpawners/435/

**Comment by timbru31** [comment]
Thanks for letting me know! Have you been able to test a dev build which has enhancements regarding plugin comparability?

**Comment by Fonzee9** [comment]
I am having the same problem..

**Comment by timbru31** [comment]
I'm cleaning up old issues. If this issue still persists, please comment here and I'll re-open this issue.
