### ISSUE TITLE
Incompatibility with 1.12.1

### ISSUE THREAD

**Issue by FrankHeijden** [timbru31/SilkSpawners#92]
## What steps will reproduce the problem?
place/break (with silk) a spawner
## Expected output
working normal
## What do you see instead?
broken
## Log file of the issue/error
https://pastebin.com/RAJyYYqk
## /version output?
CraftBukkit version git-Spigot-0d820fa-5717601 (MC: 1.12.1) (Implementing API version 1.12.1-R0.1-SNAPSHOT)

## SilkSpawners version
SilkSpawners v4.0.1-SNAPSHOT-b425

## Checklist

- [x] I am aware that issues caused by /reload are ignored
- [x] If there is a (potential) plugin conflict, I've identified the conflicting plugin
- [x] I have added a valid /version output
- [x] I have added a valid SilkSpawners version
- [x] I have attached necessary information like a screenshot, my list of plugins, config or permissions file(s)

**Comment by timbru31** [comment]
Thanks for the report and filling in the form!  
I’ll look into what’s wrong.

**Comment by baticag** [comment]
Also having problem, here's a startup error: https://www.hastebin.com/kigapesime.css
Version 1.12.1 newest PaperSpigot build

**Comment by timbru31** [comment]
@baticag please add a valid /version output. Latest is outdated pretty soon and makes things more complicated to debug.

**Comment by timbru31** [comment]
Crossreference for myself: https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/commits/19507baf8b7903427bc3efab7118de6e7c1c931e#src/main/java/org/bukkit/craftbukkit/block/CraftCreatureSpawner.java

**Comment by baticag** [comment]
Sorry, my mistake...
Paper version git-Paper-1173 (MC: 1.12.1) (Implementing API version 1.12.1-R0.1-SNAPSHOT)

**Comment by timbru31** [comment]
@baticag and @FrankHeijden please give https://ci.dustplanet.de/job/SilkSpawners/439/ a try and tell me if everything is back to normal!

**Comment by FrankHeijden** [comment]
There are no errors in console anymore, but when i place e.g. an Skeleton spawner, it immediately changes to a pig spawner when the first entity is spawned out of the spawner.

[![Screenshot from Gyazo](https://gyazo.com/2b4d4de0dce433d5cc2a021c7bd6c334/raw)](https://gyazo.com/2b4d4de0dce433d5cc2a021c7bd6c334)

**Comment by timbru31** [comment]
As a temporary workaround for 1.12.1 builds, please use an older version of Spigot/CraftBukkit by building it with BuildTools:
`java -jar BuildTools.jar --rev 1374`

**Comment by Sikatsu** [comment]
Same issue, once a spawner is placed and one mob spawns it will change to a pig spawner.

**Comment by baticag** [comment]
Also the problem with changing to pig, very urgent

**Comment by timbru31** [comment]
This is a vanilla bug, and recently fixed by the Spigot team. Latest dev build will be promoted soon! Please run BuildTools again to have a fixed CraftBukkit/Spigot version.
More information: https://bugs.mojang.com/browse/MC-92282 and https://hub.spigotmc.org/jira/browse/SPIGOT-3496
