### ISSUE TITLE
When non-opped players place spawners they turn to pigs

### ISSUE THREAD

**Issue by Chris19999** [timbru31/SilkSpawners#94]
## What steps will reproduce the problem?
Placing the spawners as a non-op
## Expected output
Spawner places as the spawners given to the player
## What do you see instead?
Spawner is placed as a pig and an error is received
## Log file of the issue/error
https://hastebin.com/ojadiquful.vbs
## /version output?
https://gyazo.com/8c6c4e454f621cc0f59517e8dd5acea5

## SilkSpawners version
version 5.0.0

## Please provide any additional information below.
Plugin list: https://gyazo.com/df12d157843afb0f3568046f672c16df
SS Config: https://hastebin.com/olicozuhuz.bash
Default players have these permissions:
    - silkspawners.place.*
    - silkspawners.explodedrop
## Checklist

- [x] I am aware that issues caused by /reload are ignored
- [ ] If there is a (potential) plugin conflict, I've identified the conflicting plugin
- [x] I have added a valid /version output
- [x] I have added a valid SilkSpawners version
- [x] I have attached necessary information like a screenshot, my list of plugins, config or permissions file(s)

**Comment by timbru31** [comment]
Can you try to disable `useWorldGuard` - can you also tell me the WorldGuard version you are using?

**Comment by Chris19999** [comment]
Seems as if disabling the world guard check works. Worldguard version is 6.1

**Comment by timbru31** [comment]
I'm cleaning up old issues. If this issue still persists, please comment here and I'll re-open this issue.
