### ISSUE TITLE
Spawner reverts back to pig after 1 use

### ISSUE THREAD

**Issue by ItsWulff** [timbru31/SilkSpawners#96]
## What steps will reproduce the problem?
Every time i place a spawner, it will change back to a pig spawner, after spawning the mobtype once.

## Expected output
Spawners stays the mob i changed it to, without turning into a pig spawner after one use.

## What do you see instead?
The spawner changes into a pig spawner after one use

## Log file of the issue/error
There is none.

## /version output?

![image](https://user-images.githubusercontent.com/15077289/30614508-ee04f898-9d8b-11e7-8294-136936b91852.png)

## SilkSpawners version
5.0.0

## Checklist

- [x] I am aware that issues caused by /reload are ignored
- [x] If there is a (potential) plugin conflict, I've identified the conflicting plugin
- [x] I have added a valid /version output
- [x] I have added a valid SilkSpawners version
- [x] I have attached necessary information like a screenshot, my list of plugins, config or permissions file(s)

**Comment by timbru31** [comment]
Please add a valid version output. Besides that your issue sounds like you are not running the latest version of Spigot/CraftBukkit.

**Comment by timbru31** [comment]
Spigot version is bugged (fix is in https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/commits/61a31ca0c7a5398d3b3e0d31469d2af58bb169f3), so run BuildTools again.
